### ISSUE TITLE
v.2.0.37-beta - cannot mock interface although it is visible

### ISSUE THREAD

**Issue by nicoruti** [mockito/mockito#341] opened 2016-01-18 09:38 UTC
After upgrading to v.2.0.37-beta maven release today, I cannot mock an interface anymore. Request is some private class within elasticsearch. Seems to be related to issue #335 . Latest version v.2.0.38-beta does not solve the issue. 

```
Mockito cannot mock this class: interface org.elasticsearch.client.Client

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalStateException: Unknown type variable: Request
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding.onTypeVariable(TypeDescription.java:2056)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding.onTypeVariable(TypeDescription.java:2013)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable.accept(TypeDescription.java:4763)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1757)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding.onParameterizedType(TypeDescription.java:2013)
	at net.bytebuddy.description.method.MethodDescription$TypeSubstituting$VariableRetainingDelegator.onParameterizedType(MethodDescription.java:1218)
	at net.bytebuddy.description.method.MethodDescription$TypeSubstituting$VariableRetainingDelegator.onParameterizedType(MethodDescription.java:1211)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:4472)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:5157)
	at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:859)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:85)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:593)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:862)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1059)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:569)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:565)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:565)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:502)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:423)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:489)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2472)
	at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:55)
	at org.mockito.Mockito.mock(Mockito.java:1449)
	at org.mockito.Mockito.mock(Mockito.java:1362)
	at BaseServiceTest$BaseServiceImpl.<init>(BaseServiceTest.java:73)
	at BaseServiceTest.mytest(BaseServiceTest.java:26)
```

**Comment by raphw** [comment] 2016-01-18 09:47
What version of elasticsearch are you using? I cannot reproduce this with 2.0.0.

**Comment by nicoruti** [comment] 2016-01-18 09:48
Sorry, forgot to specify. I'm using 1.7.3.

**Comment by raphw** [comment] 2016-01-18 09:54
Okay, I reproduced the problem. Seems to be a problem with recursive resolution of generic types. I will have a look at it some time this week.

**Comment by raphw** [comment] 2016-01-18 10:01
Its a problem in Byte Buddy. Fortunaltey, a trivial one that I can probably fix tonight: When substituting type variables of a generic super type, method type variables are bound based on the method's declaring type and not on the method. Thanks for reporting.

**Comment by raphw** [comment] 2016-01-18 20:54
Fixed in version 2.0.39-beta. Can you confirm?

**Comment by Stephan202** [comment] 2016-01-19 07:50
Yes, I observed the same issue and can confirm that 2.0.39-beta resolves it. Thanks!

**Closed** 2016-01-19 07:56 UTC

**Comment by nicoruti** [comment] 2016-01-19 08:06
Thanks for the quick fix. v2.0.39-beta works as expected.

**Comment by raphw** [comment] 2016-01-19 08:13
Thank you for testing the beta and thanks for reporting!
