### ISSUE TITLE
Mockito does not call real method with Scala Trait with concrete methods mocks. 

### ISSUE THREAD

**Issue by boonhui-lai** [mockito/mockito#340] opened 2016-01-08 12:30 UTC
import org.mockito.Mockito
import org.mockito.Mockito._
import org.scalatest.{Matchers, WordSpec}

class FooSpec extends WordSpec with Matchers {

  trait TraitWithConcreteMethods {
    def getTrue: Boolean = true
  }

  private val mockTraitWithConcreteMethods = Mockito.mock(classOf[TraitWithConcreteMethods], CALLS_REAL_METHODS)

  "mockTraitWithConcreteMethods.getTrue" should {
    "return true" in {
        val result = mockTraitWithConcreteMethods.getTrue
        result shouldBe true
      }
  }
}

//ouput
//false was not equal to true

**Comment by raphw** [comment] 2016-01-08 12:37
The problem is the way the Scala compiler implements traits: it creates an interface and a dispatcher class that contains concrete methods as static methods. Whenever a class implements a trait, the trait methods of the implenting class forward their calls to the static dispatcher.

Mockito would need to discover this and it currently does not.

**Comment by bric3** [comment] 2016-03-08 18:08
Could be a plugin for mockito that scala test could use ?
However I don't think there's a plugin interface that could allow that.

**Comment by raphw** [comment] 2016-03-08 23:24
This is not so trivial to do. We would be coding against an implementation detail of the Scala compiler. Scala does not implement "real" default methods but rather copy-pastes code. We would need to reason about the Scala code to "mean" something only from looking at the byte code. If we would do this, we should encapsulate it in a plugin as this behaviour could change in the future.

**Comment by bric3** [comment] 2016-03-09 10:25
Yep that's exactly what I have in mind. However I wanted to say that it would be the job of scala developers to maintain that code. And that the only thing mockito would provide is plugin interface(s).

**Comment by TimvdLippe** [comment] 2016-12-13 19:27
I would say we close this as won't fix, WDYT?

**Comment by bric3** [comment] 2016-12-13 22:23
This could be possible let for mockito sugar to come up with their own mock maker.
I agree let's close this as wontfix

**Closed** 2016-12-13 22:24 UTC
Labels: enhancement, wontfix
