### ISSUE TITLE
Assertion matcher

### ISSUE THREAD

**Issue by michaldo** [mockito/mockito#2960] opened 2023-04-02 20:29 UTC
`ArgumentMatcher` returns true/false and it's enough for stubs.
However, for mocks false is not enough. When expectation is not meet, it is important why not meet. It means _rich-failure_ is needed, not just `false`

Actually _rich-failure_ can be achieved with `org.assertj.core.matcher.AssertionMatcher`.
It works but it's not handy: every assertion needs a class, when lambda is enough

**Comment by TimvdLippe** [comment] 2023-04-09 13:58
Duplicate of #2285

**Closed by TimvdLippe** 2023-04-09 13:58 UTC
