### ISSUE TITLE
Mocking classes with package-private parent

### ISSUE THREAD

**Issue by Marssmart** [mockito/mockito#323] opened 2015-12-04 09:18 UTC
Hello 

i have found one bug/feature of Mockito ,which happens when you try to Mock class (in my case an library class) that has an parent class whitch has an package-private access. 

What happend is that mockito will show that the class is enhanced by mockito,but in fact it is an <b>real instance</b> of class that i was trying to mock whitch result in that this call

<code>Mockito.when(instance.method()).thenReturn(result)</code>

will call an <b>real implementation</b> of that method. 

I dont know if it is an feature or bug,buti think it will be nice to at least inform an user that he cant mock this kind of class ,like it is done with final classes.

I´ve tested to switch that parent class to public access and it works fine than ,so i looks like that it was the reason for that behaviour.

For furher details ,you can contact me at <b>jan.srnicek@globesy.sk</b>

Version of Mockito: 1.10.19

**Comment by raphw** [comment] 2015-12-04 09:45
Thanks for reporting this. The problem is already resolved in the current beta. You can either try out the beta already today or wait for the final 2.0 release. Cheers, Rafael

**Comment by bric3** [comment] 2015-12-04 10:27
For reference this issue was in the previous bugtracker ([issue 212](https://code.google.com/p/mockito/issues/detail?id=212&can=1&q=public)). The issue was probably due to the way CGLIB generated proxies. Since mockito uses ByteBuddy from @raphw many other limitations / shortcomings of CGLIB are no more.

**Closed by bric3** 2015-12-04 10:27 UTC
