### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito

### ISSUE THREAD

**Issue by kamenskyen** [mockito/mockito#2568] opened 2022-02-17 11:16 UTC
Hi, I have a some error while updating Mockito 3.12.4 -> 4.3.1

```
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:108)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.doCreateMock(DefaultMockCreator.java:61)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:53)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:126)
	at com.app.test.ExampleTest.setUp(ExampleTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Configuration:
- PowerMock 2.0.9
- Gradle 7.2.0
- Os: macOs Big Sur 11.5.2
- java 11.0.12 2021-07-20 LTS

Sample:
https://bitbucket.org/kamenskyen/testapplication/src/master/
you can change version Mockito in `build.gradle` file for `app`.

```
import android.content.Intent;

import androidx.appcompat.app.AppCompatActivity;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import static org.mockito.Mockito.verify;
import static org.powermock.api.mockito.PowerMockito.mock;
import static org.powermock.api.mockito.PowerMockito.mockStatic;
import static org.powermock.api.mockito.PowerMockito.when;

@RunWith(PowerMockRunner.class)
@PrepareForTest(SecondActivity.class)
public class ExampleTest {

    private AppCompatActivity activity;
    private Intent intent;

    @Before
    public void setUp() {
        activity = mock(AppCompatActivity.class);
        mockStatic(SecondActivity.class);
        intent = mock(Intent.class);
        when(SecondActivity.createIntentWithParam(activity)).thenReturn(intent);
    }

    @Test
    public void test() {

        MainLauncher launcher = new MainLauncher();
        launcher.startMain(activity);
        launcher.startSecond(activity);

        verify(activity).startActivity(intent);

    }

}
```

```
/**
 * Main Launcher
 */
class MainLauncher() {

    fun startMain(activity: AppCompatActivity) {
        val intent = MainActivity.createIntentWithParam(activity, "id")
        activity.startActivity(intent)
    }

    fun startSecond(activity: AppCompatActivity) {
        val intent = SecondActivity.createIntentWithParam(activity)
        activity.startActivity(intent)
    }

}
```

**Comment by TimvdLippe** [comment] 2022-02-17 23:06
I think this is a duplicate of https://github.com/powermock/powermock/issues/1112 That said, this is sadly a problem with Powermock and not Mockito. I recommend creating an issue on their issue tracker if you are still running into issues.

**Closed by TimvdLippe** 2022-02-17 23:06 UTC

**Comment by yyyyyyyysssss** [comment] 2022-07-27 08:11
我也遇到了同样的问题，麻烦问下你这个解决了嘛

**Comment by yyyyyyyysssss** [comment] 2022-07-27 08:12
I also encountered the same problem, could you please ask if you have solved this problem? How did you solve it

**Comment by Jeff-Tian** [comment] 2022-09-09 10:24
I met the same issue with org.mockito.mockito-core@4.7.0 and org.powermock.powermock-module-junit4@2.0.9. So I downgraded org.mockito.mockito-core@4.7.0 to 2.23.0, and the issue was fixed.

```diff
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
-            <version>4.7.0</version>
+            <version>2.23.0</version>
        </dependency>
```

我在使用 org.mockito.mockito-core@4.7.0 时碰到这个问题，改成 2.23.0 后，就没这个问题了。

**Comment by dduttacbre** [comment] 2022-09-20 04:31
I was having the same issue . Downgrading org.mockito.mockito-core to 2.23.0 fixed it. Thank you.

**Comment by sweety-dhale** [comment] 2022-09-21 05:12
I can't downgrade Mockito version as its project requirement and using java 11. can anyone help with the same issue??

**Comment by jlink** [comment] 2022-09-30 11:07
@sweety-dhale If it's only about Java 11, Mockito 4.4.0 seems to work here.

**Comment by icloudice** [comment] 2022-12-30 05:49
In my case. I use springboot 2.7.0+,  jdk1.8。when you update spring-boot-starter-parent to 2.7.0+. it seems that mockito-core will update to 4.5.0+。and some guys suggest Downgrading org.mockito.mockito-core to 2.23.0. but in my commpany, 2.23.0 is too old.  For my way .  12-30/2022. It`s ok to use。 Hope it useful too u.

<dependency>
    <groupId>org.powermock</groupId>
    <artifactId>powermock-api-mockito2</artifactId>
    <version>2.0.2</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <artifactId>objenesis</artifactId>
            <groupId>org.objenesis</groupId>
        </exclusion>
        <exclusion>
            <artifactId>mockito-core</artifactId>
            <groupId>org.mockito</groupId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>3.6.28</version>
    <scope>test</scope>
</dependency>

**Comment by JevanWu** [comment] 2023-04-11 10:54
I also encountered the same problem. Why is this closed?

**Comment by mrane-ea** [comment] 2023-04-12 05:29
similar proplem

**Comment by XiaoZhiSnow** [comment] 2023-05-29 07:14
> In my case. I use springboot 2.7.0+, jdk1.8。when you update spring-boot-starter-parent to 2.7.0+. it seems that mockito-core will update to 4.5.0+。and some guys suggest Downgrading org.mockito.mockito-core to 2.23.0. but in my commpany, 2.23.0 is too old. For my way . 12-30/2022. It`s ok to use。 Hope it useful too u.
> 
> ```
> <dependency>
>     <groupId>org.powermock</groupId>
>     <artifactId>powermock-api-mockito2</artifactId>
>     <version>2.0.2</version>
>     <scope>test</scope>
>     <exclusions>
>         <exclusion>
>             <artifactId>objenesis</artifactId>
>             <groupId>org.objenesis</groupId>
>         </exclusion>
>         <exclusion>
>             <artifactId>mockito-core</artifactId>
>             <groupId>org.mockito</groupId>
>         </exclusion>
>     </exclusions>
> </dependency>
> 
> <dependency>
>     <groupId>org.mockito</groupId>
>     <artifactId>mockito-core</artifactId>
>     <version>3.6.28</version>
>     <scope>test</scope>
> </dependency>
> ```
> 
> if some day I have some new update. I will paste new dependencies to here.

it is ok for me,thanks

**Comment by dotarsoyak** [comment] 2024-05-17 21:10
> In my case. I use springboot 2.7.0+, jdk1.8。when you update spring-boot-starter-parent to 2.7.0+. it seems that mockito-core will update to 4.5.0+。and some guys suggest Downgrading org.mockito.mockito-core to 2.23.0. but in my commpany, 2.23.0 is too old. For my way . 12-30/2022. It`s ok to use。 Hope it useful too u.
> 
> ```
> <dependency>
>     <groupId>org.powermock</groupId>
>     <artifactId>powermock-api-mockito2</artifactId>
>     <version>2.0.2</version>
>     <scope>test</scope>
>     <exclusions>
>         <exclusion>
>             <artifactId>objenesis</artifactId>
>             <groupId>org.objenesis</groupId>
>         </exclusion>
>         <exclusion>
>             <artifactId>mockito-core</artifactId>
>             <groupId>org.mockito</groupId>
>         </exclusion>
>     </exclusions>
> </dependency>
> 
> <dependency>
>     <groupId>org.mockito</groupId>
>     <artifactId>mockito-core</artifactId>
>     <version>3.6.28</version>
>     <scope>test</scope>
> </dependency>
> ```
> 
> if some day I have some new update. I will paste new dependencies to here.

Hi, I think this exclusions are inverted in its artifactId and groupId in both

`    <exclusions>
        <exclusion>
            <artifactId>objenesis</artifactId>
            <groupId>org.objenesis</groupId>
        </exclusion>
        <exclusion>
            <artifactId>mockito-core</artifactId>
            <groupId>org.mockito</groupId>
        </exclusion>
    </exclusions>`
