### ISSUE TITLE
MockMaker extension and spring boot

### ISSUE THREAD

**Issue by ghost** [mockito/mockito#973] opened 2017-03-02 09:50 UTC
Hi,

I have a gradle project using kotlin, mockito and spring. Due to the nature of kotlin I need to mock final classes. For that I use the MockMaker extension (by using that file"resources/mockito-extensions/org.mockito.plugins.MockMaker"). The mockito version is 2.7.5 (coming with the mockito-kotlin library).

When I try to run a test I get the following exception: 
```
Mar 02, 2017 9:12:10 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:66)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44)
	at org.mockito.Mockito.<clinit>(Mockito.java:975)
	at com.nhaarman.mockito_kotlin.MockitoKt.withSettings(Mockito.kt:265)
	at de.weltn24.mocking.ClassToTestSpec$1$1.invoke(ClassToTestSpec.kt:35)
	at de.weltn24.mocking.ClassToTestSpec$1$1.invoke(ClassToTestSpec.kt:10)
	at org.jetbrains.spek.engine.SpekTestEngine$Collector.group(SpekTestEngine.kt:148)
	at org.jetbrains.spek.api.dsl.SpecBody$DefaultImpls.group$default(SpecBody.kt:13)
	at org.jetbrains.spek.api.dsl.StandardKt.describe(Standard.kt:10)
	at de.weltn24.mocking.ClassToTestSpec$1.invoke(ClassToTestSpec.kt:11)
	at de.weltn24.mocking.ClassToTestSpec$1.invoke(ClassToTestSpec.kt:10)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:114)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:76)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:48)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:109)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 31 more
```
If I remove the spring boot plugin from the build.gradle the test works fine. I have attached a sample project to reproduce this issue.

[mocking.zip](https://github.com/mockito/mockito/files/813341/mocking.zip)

**Comment by TimvdLippe** [comment] 2017-03-19 21:05
The stacktrace indicates that [`registry`](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/internal/configuration/plugins/Plugins.java#L23) is `null`. That should not be possible given that it is initialized when the class is loaded. Unsure what could be going wrong here from Mockito. It probably is an issue with Spring Boot?

**Comment by Hendrik-AS** [comment] 2017-03-22 07:35
hm its kind of weird since I do not see how third party code could influence that registry. Anyways my solution now was to put everything I want to test into another module ...

**Comment by kpronovost** [comment] 2017-06-19 18:54
FYI, I just had this issue, using 2.8.47.

**Comment by samlindsaylevine** [comment] 2017-07-13 16:15
I am also experiencing this problem. I also came to it while using Kotlin, but I believe that is not necessary to reproduce this issue: I could reproduce it using a Java-only Spring Boot project, with the same symptom.

**Comment by TimvdLippe** [comment] 2017-10-03 10:08
Per the above comment, can you reproduce this problem with the latest version of mockito (2.10.0)?

**Comment by SanjayMallur** [comment] 2017-12-18 11:07
@TimvdLippe I am able to reproduce this issue with 2.10.0, below are my logs:

java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:30)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:19)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.ClassPathLoader.loadImplementations(ClassPathLoader.java:145)
	at org.mockito.internal.configuration.ClassPathLoader.findPluginImplementation(ClassPathLoader.java:110)
	at org.mockito.internal.configuration.ClassPathLoader.findPlatformMockMaker(ClassPathLoader.java:106)
	at org.mockito.internal.configuration.ClassPathLoader.<clinit>(ClassPathLoader.java:59)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:21)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
	at org.mockito.Mockito.<clinit>(Mockito.java:932)
	at com.tippingcanoe.urlaubspiraten.data.source.model.BookingItemTest.<init>(BookingItemtest.kt:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 38 more


Process finished with exit code 255

**Comment by lorochka** [comment] 2018-02-22 22:31
I want to add some information: this extension does work with mockito-core 2.10.0 and Springboot. Everyone, who experience this behavior, should build the dependency tree and see which version of Mockito you have.

**Comment by AAverin** [comment] 2018-03-07 16:05
The only solution for us so far have been extracting everything to another module
The problem is that when ApplicationContext class is in a different module `@SpringBootTest` can't discover it and I can't write integration tests.
Any fixes for this problem?

**Comment by bolerio** [comment] 2018-04-17 03:09
I have this problem without any extra frameworks with a special init sequence (like Spring Boot etc.). A plain main program using gRPC as a communication protocol. Doing it at the beginning of the test itself (as opposed to @BeforeClass or even @Before method) doesn't help either.

**Comment by dianov** [comment] 2018-07-27 12:43
I've got the same java.lang.ExceptionInInitializerError
I used Spting Boot @MockBean annotation + Kotlin + mockito-inline:2.19.1

**Comment by JakubParzonka** [comment] 2019-02-26 09:58
Same issue. Spring boot test starter 1.4.3

**Comment by antalk** [comment] 2019-03-18 07:58
I've got the same stacktrace but with cdi-unit extension:

Using maven and mockito version 1.10.19

java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:66)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues.<init>(ReturnsEmptyValues.java:58)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsMoreEmptyValues.<init>(ReturnsMoreEmptyValues.java:51)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsSmartNulls.<init>(ReturnsSmartNulls.java:40)
	at org.mockito.Answers.<clinit>(Answers.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
	at java.lang.Class.enumConstantDirectory(Class.java:3341)
	at java.lang.Enum.valueOf(Enum.java:232)
	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:483)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:347)
	at java.lang.reflect.Method.getDefaultValue(Method.java:606)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:132)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1150)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1148)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1139)
	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:207)
	at org.junit.runners.model.FrameworkField.getAnnotations(FrameworkField.java:31)
	at org.junit.runners.model.TestClass.addToAnnotationLists(TestClass.java:84)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:71)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.jglue.cdiunit.CdiRunner.<init>(CdiRunner.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 57 more

**Comment by walaniam** [comment] 2019-06-13 14:38
The issue seems to be in org.mockito.internal.configuration.plugins.PluginLoader class. When resolving mock maker plugin class (code below) there is a "mock-maker-inline" returned but I guess there should be a fully qualified class name returned. It results in MockitoException thrown which is next suppressed. 
`String foundPluginClass = new PluginFinder(pluginSwitch).findPluginClass(Iterables.toIterable(resources));`

**Comment by jdai8** [comment] 2021-05-05 00:04
I was able to fix this by removing an old version of `org.mockito:mockito-all` that was being pulled onto my runtime classpath. Presumably there were duplicate versions of mockito classes on the classpath, since these are published at different coordinates.

Note that `mockito-all` has been discontinued in favor of `mockito-core`.

Hope this helps anyone else running into this issue.

**Comment by TimvdLippe** [comment] 2023-05-06 18:46
Closing per the above comment.

**Closed by TimvdLippe** 2023-05-06 18:46 UTC
