### ISSUE TITLE
NullPointerException when stubbing a class in Groovy 2.3.6

### ISSUE THREAD

**Issue by marcingrzejszczak** [mockito/mockito#72] opened 2014-08-12 08:12 UTC
**Setup**
Groovy 2.3.6
Mockito 1.9.5
JDK 8

**Given** a test written in Groovy
```
package com.ofg.twitter.controller.place.extractor

import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.Mock

import static org.mockito.Mockito.when

@RunWith(MockitoJUnitRunner)
class MockitoTest {
    
    private static final String PAID = 'PAID'

    @Mock PaymentOrderStatusChecker checkerMock
    
    @Test
    void testSth() {
        String paymentOrderId = "examplePaymentOrderIdUsedInTests1"
        
        when(checkerMock.checkStatus(paymentOrderId)).thenReturn(PAID)
        
        assert checkerMock.checkStatus(paymentOrderId) == PAID
    }
}

class PaymentOrderStatusChecker {
    String checkStatus(String status) {
        return ''
    }
}

```

**When** I exeucte the code

**Then** I receive

```
java.lang.NullPointerException
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.ofg.twitter.controller.place.extractor.MockitoTest.testSth(MockitoTest.groovy:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by xnickmx** [comment] 2015-02-22 23:54
A very similar problem recently happened to me. I got a NullPointerException in PogoMetaClassSite, where the metaClass was null during a unit test. I was using mockito-groovy-support. 

Then I noticed that the version of mockito-groovy-support depended on Mockito 1.9.5. In my project was using Mockito 1.8.5. After upgrading my version, everything worked.

**Comment by bric3** [comment] 2015-02-23 10:05
@xnickmx Cool thanks for the feeback

**Comment by hekonsek** [comment] 2015-07-16 09:19
The same here. mockito-groovy-support solved the issue for me, however it would be nice to have the root cause of the issue fixed in Mockito, instead of relaying on the 3rd aprty jar. @moss Can you consider issuing the pull request to Mockito with your fixes? You will make many folks happy ;) .

**Comment by raphw** [comment] 2015-07-16 11:12
Problem would be that the workarround requires Groovy on the class path. One could avoid this by using reflection. Also, I wonder if there is a better way to check if a method is for retreiving the Groovy meta class than by checking the signature of the method as the current approach would break non-Groovy classes defining a method named `getMetaClass`.

One could however wire this. I do not think an auto-detection would be difficult to implement.

**Comment by raphw** [comment] 2015-07-16 11:31
This should do the trick: https://github.com/raphw/mockito/commit/32340365469b99ec5ad2cf2c87b7a79cc472118b

Any objections against this approach?

**Comment by bric3** [comment] 2015-07-16 16:26
I have mixed feelings about these changes, but I must agreed this certainly looks like a simple enough solution. @raphw Make a PR :)

**Comment by raphw** [comment] 2015-07-16 16:34
Will do tomorrow. Simply ignoring the methods is actually easier.

**Comment by hekonsek** [comment] 2015-07-16 19:08
Many thanks guys!

**Comment by raphw** [comment] 2015-07-17 12:02
Okay, I pushed a change and put a pull request on the line. Using this, Mockito should support Groovy out of the box.

**Comment by PascalSchumacher** [comment] 2015-12-17 03:51
@raphw I guess this can be closed because Mockito is now using a byte buddy version with your fix?

**Comment by raphw** [comment] 2015-12-17 07:41
You are right.

**Closed by raphw** 2015-12-17 07:41 UTC
