### ISSUE TITLE
Can ThrowsException be made part of Answers so it can be used with @Mock?

### ISSUE THREAD

**Issue by avamsi** [mockito/mockito#1666] opened 2019-03-17 15:14 UTC
>  - [ ] ~The mockito message in the stacktrace have useful information, but it didn't help~
>  - [ ] ~The problematic code (if that's possible) is copied here;
>        Note that some configuration are impossible to mock via Mockito~
>  - [ ] ~Provide versions (mockito / jdk / os / any other relevant information)~
>  - [ ] ~Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
>        (same as any question on stackoverflow.com)~
>  - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

I wanted to make ThrowsException the default Answer to as many mocks as possible through-out our tests and was pretty surprised to find out it's not part of the Answers enum. Can it be included?

**Comment by TimvdLippe** [comment] 2019-03-17 20:20
That answer is an implementation detail of `thenThrow`. What is your motivation for wanting to always throw an exception?

**Comment by avamsi** [comment] 2019-03-18 02:24
In my experience (anecdotal, me and my peers), not setting up a mock properly is one of the most frustrating things to debug, not because it's hard but because it ideally wouldn't have happened in the first place (if the mock was just configured to throw) and (IMO) it's a low cost fix as well. WDYT?

**Comment by TimvdLippe** [comment] 2019-03-18 14:09
I think the feature you are looking for is strict mocks: https://static.javadoc.io/org.mockito/mockito-core/2.25.1/org/mockito/Mockito.html#40 is it not?

**Comment by avamsi** [comment] 2019-03-18 15:21
On the surface, it looks like slightly different from what I want (for example, if I have multiple when statements using various Matchers and one of them match, it looks strict mocks would throw(?) where as, a mock with an Answer similar to ThrowsException would only throw if none of them match, although I'm not sure how common it is to have multiple when statements in practice).

I'll take a deeper look tomorrow and get back to you. Thanks!

**Comment by TimvdLippe** [comment] 2019-08-11 13:50
Closing this as working as intended. If you can provide a use case for Mockito where the current API is less than optimal, please reopen.

**Closed by TimvdLippe** 2019-08-11 13:50 UTC

**Comment by OrangeDog** [comment] 2020-02-06 17:51
A default answer of `ThrowsException` would be similar to `verifyNoInteractions()`, but failing immediately instead of at the end.

However, I don't see how it can go in the `Answers` enum as it needs a parameter of what to throw.
