### ISSUE TITLE
StackWalker.Option not found on Mockito 5.1.0

### ISSUE THREAD

**Issue by sergiandreplace** [mockito/mockito#2890] opened 2023-01-30 10:32 UTC
We have an Android project using Mockito and we tried to upgrade from 5.0.0 to 5.1.0.

When running the Android tests we always receive an error like this:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/StackWalker$Option;
	at org.mockito.internal.debugging.LocationImpl.stackWalker(LocationImpl.java:138)
	at org.mockito.internal.debugging.LocationImpl.<clinit>(LocationImpl.java:40)
	at org.mockito.internal.debugging.LocationFactory.create(LocationFactory.java:17)
	at org.mockito.internal.debugging.LocationFactory.create(LocationFactory.java:13)
	at org.mockito.internal.matchers.LocalizedMatcher.<init>(LocalizedMatcher.java:19)
	at org.mockito.internal.progress.ArgumentMatcherStorageImpl.reportMatcher(ArgumentMatcherStorageImpl.java:30)
	at org.mockito.ArgumentMatchers.reportMatcher(ArgumentMatchers.java:1036)
	at org.mockito.ArgumentMatchers.any(ArgumentMatchers.java:177)
	...
```

After some investigation we found that:

* StackWalker is only available from Java 9. All our modules are setup to use Java 11.
* We can't see StackWalker class from the IDE
* This only happens on Android instrumental tests, not in "normal" java tests
* The class StackWalker is not available in Android SDK java implementation: https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-33/tree/master/java/lang (that would explain why is not working only for instrumental tests, as they are executed on an Android device). Checked for latest android versions.

It looks like a very specific Android issue.

For the meantime, we will halt the upgrade, but any help will be great.

Thanks in advance

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [N/A] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment] 2023-01-30 14:30
Two questions:
1. Are you using `mockito-android`?
2. Does a later version of Android ship the API?

**Comment by zsoltvilagos** [comment] 2023-01-30 15:02
@TimvdLippe I hope @sergiandreplace doesn't mind if I answer.

We're also using Mockito and ran into the very same problem.

> 1. Are you using `mockito-android`?
We're using `mockito-android`, same version 5.1.0 as `mockito-core`.

> 2. Does a later version of Android ship the API?

Nope. API 33 is the latest version, Android 13.

**Comment by SmasSive** [comment] 2023-01-30 15:16
@TimvdLippe a colleague of Sergi here! Yes, we are using mockito-android (5.1.0 same version of core).
And as @zsoltvilagos said, no... The latest version of Android (SDK 33) does not include the API.

**Comment by TimvdLippe** [comment] 2023-01-30 16:41
@reta if I understand correctly, we would have to revert the StackWalker change, but that would break your integration with the `SecurityManager`. Can we figure out a solution that would satisfy both?

**Comment by reta** [comment] 2023-01-30 16:48
@TimvdLippe unexpected, but I agree, we probably have to revert at least the  `StackWalker`  changes and use the reflection for Android, sorry about that. I could look into it tonight if that is fine with you. Thank you.

**Comment by TWiStErRob** [comment] 2023-01-30 17:01
Here's a minimal repro in case you want to test things out (or add an integration test for a basic case): 
1. https://github.com/TWiStErRob/repros/tree/master/mockito/mockito5_StackWalkerOption
2. Unit Tests: `gradlew testDebugUnitTest`  
   report: `./build/reports/tests/testDebugUnitTest/index.html`
3. Instrumentation Tests: `gradlew connectedCheck`  
   report: `./build/reports/androidTests/connected/index.html`
4. Instrumentation Tests (alternative): `gradlew pixel2api33DebugAndroidTest`  
   report: `./build/reports/androidTests/managedDevice/allDevices/index.html`

Note: `connectedCheck` and `pixel2api33DebugAndroidTest` are almost equivalent, but `pixel2api33DebugAndroidTest` only needs an SDK installed, it will download and set up the emulator automatically.

I used a realistic but pointless mocking setup, also it repros using just `mock()` too.

## Results
Mockito 5.1.0 (committed to repro):
 * `gradlew testDebugUnitTest`: ✅ passes
 * `gradlew connectedCheck`: ❌ fails  
   `NoClassDefFoundError: Failed resolution of: Ljava/lang/StackWalker$Option;`
 * `gradlew pixel2api33DebugAndroidTest`: ❌ fails  
   `NoClassDefFoundError: Failed resolution of: Ljava/lang/StackWalker$Option;`

Mockito 5.0.0 (for control, change `def mockito` in `build.gradle`):
 * `gradlew testDebugUnitTest`: ✅ passes
 * `gradlew connectedCheck` (API 21): ❌ fails  
   `NoClassDefFoundError: org.mockito.internal.invocation.TypeSafeMatching$$ExternalSyntheticLambda0`
 * `gradlew connectedCheck` (API 31): ✅ passes
 * `gradlew pixel2api33DebugAndroidTest` (API 33): ✅ passes

Mockito 4.11.0 (for control, change `def mockito` in `build.gradle`):
 * `gradlew testDebugUnitTest`: ✅ passes
 * `gradlew connectedCheck` (API 21): ❌ fails  
   `NoClassDefFoundError: org.mockito.internal.invocation.TypeSafeMatching$$ExternalSyntheticLambda0`
 * `gradlew connectedCheck` (API 31): ✅ passes
 * `gradlew pixel2api33DebugAndroidTest` (API 33): ✅ passes

For reference: https://developer.android.com/reference/classes doesn't have `StackWalker`.

**Comment by TimvdLippe** [comment] 2023-01-30 19:17
FWIW we started an effort to set up some basic Android tests for us: https://github.com/mockito/mockito/tree/main/subprojects/androidTest However, this stalled as we couldn't get it to work on CI. If anybody affected here would like to dedicate some time to prevent these kind of issues from happening, please take a look at the existing test suite and infrastructure and submit a PR to get it passing on CI.

**Closed** 2023-01-30 22:22 UTC

**Comment by zsoltvilagos** [comment] 2023-01-31 05:54
@TimvdLippe @reta Thanks a lot of the awesome fast reaction & fix. Great.

**Comment by sergiandreplace** [comment] 2023-01-31 07:41
Wow, that was fast. Thanks a lot for the solution!

**Comment by TWiStErRob** [comment] 2023-01-31 08:29
Confirmed working on the PR I had linked above.
Thanks for the quick turnaround.

Is there a tracking issue for Android CI?
I have a working GHA with Espresso tests (the key was running on Mac):
https://github.com/TWiStErRob/net.twisterrob.colorfilters/blob/master/.github/workflows/CI.yml#L177

**Comment by reta** [comment] 2023-01-31 12:50
@TWiStErRob thank you!

> Is there a tracking issue for Android CI?

Yes, https://github.com/mockito/mockito/issues/2892

**Comment by TWiStErRob** [comment] 2023-02-05 09:54
A quick update for watchers and posterity.

The above problem was caused by removing [Java 8 support](https://github.com/mockito/mockito/issues/2879) in [this PR](https://github.com/mockito/mockito/pull/2883), and the fix was to [partially revert the removal](https://github.com/mockito/mockito/pull/2891).

After the fix and patch release, we added Android CI with reta (reviewed by TimvdLippe):
 * https://github.com/mockito/mockito/pull/2893
 * https://github.com/mockito/mockito/pull/2899
 * https://github.com/mockito/mockito/pull/2894

---

`@Androids`, could you please take a look if you agree the these are sufficient to prevent future breakages like this issue?

CI: https://github.com/mockito/mockito/blob/ebdca97dfbef6e8cf35944e9cb9244672d86e12f/.github/workflows/ci.yml#L88-L125
Android Integration test project: https://github.com/mockito/mockito/tree/main/subprojects/androidTest
