### ISSUE TITLE
Mocking a function with a default implementation but no concrete implementation generates an error

### ISSUE THREAD

**Issue by emosesSfdc** [mockito/mockito#329] opened 2015-12-22 23:09 UTC
This behavior worked in 2.0.26-beta but causes an error in 2.0.33-beta.  

See https://github.com/emosesSfdc/mockito-default-mock-repro for a repro case.  Its tests pass in .26, but one of them fails in .33 with the error:

```
Cannot call abstract real method on java object!
Calling real methods is only possible when mocking non abstract method.
  //correct example:
  when(mockOfConcreteClass.nonAbstractMethod()).thenCallRealMethod();
org.mockito.exceptions.base.MockitoException: 
Cannot call abstract real method on java object!
Calling real methods is only possible when mocking non abstract method.
  //correct example:
  when(mockOfConcreteClass.nonAbstractMethod()).thenCallRealMethod();
	at mockitoTest.ApplicationTest.testGetValue(ApplicationTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

If you have an interface 

```
public interface I {
    default String m() { return "m"; }
}
```

And a concrete implementation that doesn't override `m()`, 

```
public class Impl implements I {}
```

Then if you try 

```
I i = Mockito.spy(new Impl());
Mocktio.when(i.m()).thenReturn("other");
i.m();
```

You'll get the above error.

**Comment by raphw** [comment] 2015-12-23 10:48
I do not have my computer on me but I will check this out and fix it right after new year. Thanks for reporting.

**Comment by raphw** [comment] 2015-12-30 12:36
I found the error, I added a new validation rule for when a default method is invokeable from a generated class and made a mistake. It is now fixed and I push a new version at the end of this week. I will make sure there is a test case for it, sorry for this, we still support Java 6 what makes testing Java 8 specific features a bit tricky.

**Comment by raphw** [comment] 2016-01-04 08:57
This problem should now be solved with the latest beta.

**Closed** 2016-01-04 13:08 UTC
Labels: bug

**Comment by bric3** [comment] 2016-01-04 13:11
For reference thanks to Byte Buddy 0.7.8, that @raphw fixed in commit 0775458a29740029d60e2c66c9081ab8a66900dd. The fix version is 2.0.36-beta

**Comment by emosesSfdc** [comment] 2016-01-04 19:41
Thanks!

**Comment by danparisi** [comment] 2021-12-17 09:57
In mockito-core 3.0.0 the issue is still there
