### ISSUE TITLE
There is issue with generics and mock

### ISSUE THREAD

**Issue by solairerove** [mockito/mockito#1056] opened 2017-04-29 10:15 UTC
So issue:

I have some generic interface:

```java
public interface Service<T> {

    /**
     * Persist entity in document
     *
     * @param entity the saved model
     * @return T's id
     */
    String persist(T entity);
}
```

The first implementation:

```java
@Service
public class FirstService implements Service<Model> {
    
    @Override
    public String persist(final Model entity) {
    }
}
```

The second implementation: 

```java
@Service
public class SecondService implements Service<OtherModel> {
    
    @Override
    public String persist(final OtherModel entity) {
    }
}
```

These both services use in some manager, that i want to test:

```java
@Service
public class Manager implements Management {

    private final Service<Model> firstService;

    private final Service<OtherModel> secondService;

    @Autowired
    public Manager(final Service<Model> firstService,
                   final Service<OtherModel> secondService) {
     }
}
```

Manager mock test:

```java

@RunWith(MockitoJUnitRunner.class)
public class ManagerTest {

    @Mock
    private FirstService firstService;

    @Mock
    private SecondService secondService;

    @InjectMocks
    private Manager manager;
}

```

So here is a lot of problems with tests passing, class loader and casting. But when i use old style like this:

```java

@RunWith(MockitoJUnitRunner.class)
public class ManagerTest {

    private FirstService firstService;

    private SecondService secondService;

    private Manager manager;
   
    @Before
    public void setUp() {
        firstService = mock(FirstService.class);
        secondService = mock(SecondService.class);

        manager = new Manager(firstService, secondService);
    }
}

```

It's ok, and all tests pass, and i have any troubles.

Fails:
- `java.lang.ClassCastException: com.github.package.model.Model`
- `Wanted but not invoked:`
- `ClassNotFound`

Versions:
- `springBootVersion=1.5.3.RELEASE`
- `mockitoVersion=1.10.19` and `mockitoVersion=2.0.2-beta`

Env:

```bash
➜  git:(master) java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

➜ git:(master) gradle -v

------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.4 x86_64
```

**Comment by raphw** [comment] 2017-04-29 10:31
Have you tried with a more recent version? We fixed a lot of bugs since.

**Comment by solairerove** [comment] 2017-04-29 10:41
@raphw yep. I use `mockitoVersion=1.10.19 or mockitoVersion=2.0.2-beta`

**Comment by raphw** [comment] 2017-04-29 10:54
We are long past the beta.

**Comment by solairerove** [comment] 2017-04-29 12:21
@raphw now i use `mockitoVersion=2.7.22` and i have the same issues

**Comment by Ghedeon** [comment] 2017-05-06 11:43
It's actually a duplicate of #1066. It's not fixed in 2.8.28. From what I see, `PropertyAndSetterInjection` takes generic types and `@Mock`' name attributes into account, so it works as expected for the field injection. But it doesn't work with constructors because `ConstructorInjection` is using only `SimpleArgumentResolver` which is well... very simple and doesn't have any `MockCandidateFilter` like property injector does. I feel like it would benefit to unify the filtering logic between these two types of injection in order to bring some consistency but I'm afraid I'm not familiar with your codebase enough.

**Comment by Meaaow** [comment] 2020-09-20 22:03
I am also facing the same issue - https://github.com/mockito/mockito/issues/2041

**Comment by CharlesZ-Chen** [comment] 2021-07-27 21:24
Any update to this issue?

**Comment by TimvdLippe** [comment] 2021-10-17 20:41
Duplicate of #1066

**Closed by TimvdLippe** 2021-10-17 20:41 UTC
Labels: injection
