### ISSUE TITLE
IllegalAccessError on Java 11 when using module path

### ISSUE THREAD

**Issue by marx-freedom** [mockito/mockito#1577] opened 2018-12-27 10:59 UTC
Mockito cannot mock package private class when tests running with module path. It trying to use reflection and defineClass method by default and this does not work on Java 11. I've found PR #1355 and tried to use org.mockito.internal.simulateJava11 system property but it doesn't works either.

I'm using:
Java 11 (release), Maven 3.6.0, surefire-maven-plugin 3.0.0-M3, JUnit 5.3.2, Mockito 2.23.4 (2.23.11 have same issue).

With this configuration mockito and byte buddy are included in classpath, my modular jar is included in module path, and module system is configured correctly (I suppose :)).

You can check this on minimal sample project: [mockito-java11-jpms-example.zip](https://github.com/mockito/mockito/files/2712255/mockito-java11-jpms-example.zip) - just run `mvn clean test`.

Stacktrace
```
Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.invoke.MethodHandles$Lookup#defineClass                                                                              
        at test.marx.mockito/test.marx.mockito.ServiceTest.testMockito(ServiceTest.java:17)                                                                                                           
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                             
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                           
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                   
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                 
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)                                                                                                     
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)                                                                                                    
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)                                                                  
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)                                                                                      
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)                                                                           
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)                                                                                    
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)                                                                                     
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)                                                                             
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)                                                                                      
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)                                                                                       
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)                                                                                                  
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)                                                                                                                                 
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)                                      
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)                                                                             
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)                                                                                      
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)                                                                                       
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)                                                                                                  
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)                                                                                                                                 
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)                                      
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)                                                                             
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)                                                                                      
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)                                                                                       
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)                                                                                                  
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)                                         
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)                                                                          
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)                                                                              
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)                                                                                                         
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)                                                                                                
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)                                                                                          
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)                                                                                                         
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)                                                                                                         
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)                                                                               
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)                                                                                       
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)                                                                                       
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)                                                                                                    
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)                                                                                                               
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)                                                                                                                  
Caused by: java.lang.IllegalStateException: Error invoking java.lang.invoke.MethodHandles$Lookup#defineClass                                                                                          
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$Dispatcher$ForJava9CapableVm.defineClass(ClassInjector.java:1686)                                                                  
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1415)                                                                                                 
        at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:111)                                                                                                    
        at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:466)                                                                                         
        at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)                                                                                           
        at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5623)                                                                                                             
        at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:129)                                                                            
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)                                                                          
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)                                                                          
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)                                                                                                                                   
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)                                                                                                              
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)                                                                                                                                   
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)                                                                                                              
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)                                                                       
        at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)                                                                      
        at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)                                                                          
        at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)                                                                                          
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)                                                                                                                            
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:69)                                                                                                                                 
        at org.mockito.Mockito.mock(Mockito.java:1896)                                                                                                                                                
        at org.mockito.Mockito.mock(Mockito.java:1805)                                                                                                                                                
        ... 42 more                                                                                                                                                                                   
Caused by: java.lang.IllegalAccessError: class org.mockito.codegen.IDependency$MockitoMock$1828864830 cannot access its superinterface test.marx.mockito.Service$IDependency (org.mockito.codegen.IDependency$MockitoMock$1828864830 is in unnamed module of loader 'app'; test.marx.mockito.Service$IDependency is in module test.marx.mockito of loader 'app')                                            
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)                                                                                                                                
        at java.base/java.lang.System$2.defineClass(System.java:2123)                                                                                                                                 
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)                                                                                                        
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                             
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                           
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                   
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                 
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$Dispatcher$ForJava9CapableVm.defineClass(ClassInjector.java:1682)                                                                  
        ... 62 more                                                                                                                                                                                   ```

**Comment by raphw** [comment] 2018-12-27 14:52
you have to open your module to the unnamed module where mockito is set to make this work.

**Comment by marx-freedom** [comment] 2018-12-27 15:47
@raphw I'm using this configuration:

```
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- test code needs access to package private level, so we use add-opens -->
                    <argLine>
                        --add-opens test.marx.mockito/test.marx.mockito=ALL-UNNAMED
                    </argLine>
                    <systemPropertyVariables>
                        <!-- this hidden property force mockito to use method lookup -->
                        <org.mockito.internal.simulateJava11>true</org.mockito.internal.simulateJava11>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```

Maybe I'm missing something...

**Comment by raphw** [comment] 2019-01-05 23:51
I see what the problem is now. Java considers all packages that belong to a named module to be sealed. Therefore, our mock creation strategy is oversensitive and defines the mock in another package such that the super type is no longer visible.

Let me look into this for a bit. We will fix this in an upcoming release.

**Comment by raphw** [comment] 2019-01-06 00:14
@marx-freedom Could you check out this branch, build Mockito and see if it works?

**Comment by marx-freedom** [comment] 2019-01-14 20:43
@raphw I've tried it today, but it doesn't works as expected.
With -Dorg.mockito.internal.simulateJava11=true test throws exception:

```
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface test.marx.mockito.Service$IDependency.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11+28
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11+28
JVM info           : mixed mode
OS name            : Windows 10
OS version         : 10.0


Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.invoke.MethodHandles$Lookup#defineClass
	at test.marx.mockito/test.marx.mockito.ServiceTest.testMockito(ServiceTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.invoke.MethodHandles$Lookup#defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$Dispatcher$ForJava9CapableVm.defineClass(ClassInjector.java:1686)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1415)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:111)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:466)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5623)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:129)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1896)
	at org.mockito.Mockito.mock(Mockito.java:1805)
	... 42 more
Caused by: java.lang.IllegalAccessError: class org.mockito.codegen.IDependency$MockitoMock$2018315156 cannot access its superinterface test.marx.mockito.Service$IDependency (org.mockito.codegen.IDependency$MockitoMock$2018315156 is in unnamed module of loader 'app'; test.marx.mockito.Service$IDependency is in module test.marx.mockito of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2123)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$Dispatcher$ForJava9CapableVm.defineClass(ClassInjector.java:1682)
	... 62 more

```


Should I use system property org.mockito.internal.simulateJava11 or there is any other setup tasks I'm missing?


One little idea. I've wrote something like this recently, it works with module path and custom module layers. But I've tested it only for custom classes, not in standard packages like `java.*`.  

```
class SomeFactory {

    public <C> C createDynamicSubclass(Class<C> clazz) {

        getClass().getModule().addReads(clazz.getModule());

        var dynamicClass = new ByteBuddy()
                .subclass(clazz, ConstructorStrategy.Default.IMITATE_SUPER_CLASS)
                .defineField(...)
                ...
                .make()
                .load(clazz.getClassLoader(), ClassLoadingStrategy.UsingLookup.of(
                        MethodHandles.privateLookupIn(clazz, MethodHandles.lookup()))
                )
                .getLoaded();

        return dynamicClass.getConstructor(new Class<?>[] {}).newInstance();
    }
```

**Comment by raphw** [comment] 2019-01-14 21:32
I have worked quite a bit on this over the last days. I just checked in several changes in the last hour. I also managed to write a bunch of unit tests now and hope that it works as I expect it.

**Closed** 2019-01-14 21:48 UTC
Labels: in progress

**Comment by marx-freedom** [comment] 2019-01-17 22:41
@raphw Thank you very much! Mockito 2.23.16 works perfectly, problem solved.
