### ISSUE TITLE
Unable to migrate from Mockito 2.23.4 to 2.24.x or 2.25.x

### ISSUE THREAD

**Issue by marcam** [mockito/mockito#1671] opened 2019-03-21 12:20 UTC
Hi,
while trying to upgrade mockito from 2.23.4 to 2.24 or 2.25, whe have tge following error :

```
testXXXs(xxx.TestXXX)  Time elapsed: 0.093 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface org.springframework.security.core.context.SecurityContext.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.161-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_161-b12
JVM info           : mixed mode
OS name            : Windows 7
OS version         : 6.1


Underlying exception : java.lang.IllegalArgumentException: Could not create type
	at testXXXs(xxx.TestXXX).java:66)
Caused by: java.lang.IllegalArgumentException: Could not create type
	at testXXXs(xxx.TestXXX).java:66)
Caused by: java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.MultipleParentClassLoader$Builder.appendMostSpecific(Ljava/util/Collection;)Lnet/bytebuddy/dynamic/loading/MultipleParentClassLoader$Builder;
	at testXXXs(xxx.TestXXX).java:66)
```

In the java code the error is here (line 66):
```
// Mock for SpringContext
SecurityContext securityContext = Mockito.mock(SecurityContext.class);
```

Many thanks for your help,

Marc

**Comment by TimvdLippe** [comment] 2019-03-21 12:24
Closing as duplicate of #1606. You need to use a more recent version of ByteBuddy.

**Closed by TimvdLippe** 2019-03-21 12:24 UTC
