### ISSUE TITLE
[Kotlin] Mocking fails when one suspend function calls other suspend function

### ISSUE THREAD

**Issue by rciurkot** [mockito/mockito#1152] opened 2017-07-26 16:21 UTC
When trying to mock class that has `suspend` function that calls other `suspend` function, it fails with exception: 
```
Exception in thread "main" org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: class com.myapp.SuspendableClass.
Can not mock final classes with the following settings :
- explicit serialization (e.g. withSettings().serializable())
- extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class com.myapp.SuspendableClass]
at com.myapp.DupaKt$main$1.doResume(dupa.kt:25)
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189)
at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129)
at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:225)
at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150)
at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142)
at com.myapp.DupaKt.main(dupa.kt:24)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class com.myapp.SuspendableClass]
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
... 9 more
Caused by: java.lang.IllegalStateException:
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
- Compiled by older versions of scalac
- Classes that are part of the Android distribution
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:120)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:97)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:201)
at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:182)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
at org.mockito.Mockito.mock(Mockito.java:1729)
at org.mockito.Mockito.mock(Mockito.java:1642)
... 9 more
Caused by: java.lang.IllegalStateException: public final java.lang.Object com.myapp.SuspendableClass.fetch(boolean,kotlin.coroutines.experimental.Continuation) is inconsistent at 1: java/lang/Object
at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1200)
at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1141)
at net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:6636)
at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2910)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1628)
at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:167)
at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:117)
... 23 more

Process finished with exit code 1
```

This is the simples example I could come up with to present this bug:
```
class SuspendableClass {
    suspend fun fetch(updateOnly: Boolean = true): Int {
//uncomment to fix mocking
//        runBlocking {
        fetchConcrete()
//        }
        return 2
    }

    suspend fun fetchConcrete() = 1
}

fun main(args: Array<String>) = runBlocking<Unit> {
    val mockClass = Mockito.mock(SuspendableClass::class.java)

    Mockito.`when`(mockClass.fetch()).thenReturn(10)

    MatcherAssert.assertThat(mockClass.fetch(), IsEqual(10))
    Mockito.verify(mockClass).fetch()
}
```

Important notes:
- mock-maker-inline is used to mock `final` classes
- mockito version: 2.8.47
- making class and all it's methods `open` allows mocking
- running inner `suspend` function inside `runBlocking` allows mocking

**Comment by TimvdLippe** [comment] 2017-07-26 19:51
Paging @elizarov as the original author of suspending function support.

**Comment by szczepiq** [comment] 2017-08-13 14:20
Thank you for descriptive report and submitting a sample! @elizarov, @raphw, any thoughts about this issue?

**Comment by raphw** [comment] 2017-08-14 07:06
This has nothing to do with the fact that these functions are suspended but is probably a bug in the Kotlin compiler:

> Caused by: java.lang.IllegalStateException: public final java.lang.Object com.myapp.SuspendableClass.fetch(boolean,kotlin.coroutines.experimental.Continuation) is inconsistent at 1: java/lang/Object

Byte Buddy complains that the Kotlin compiler specified a stack map frame of type `Object` for the function where it expects a `boolean` (at index 1). This means that the Kotlin compiler overrides the original arguments of the method with new local variables what makes it impossible to - for example - extract them for calling the original method. It is simply not possible to instrument it for us.

I would report this to the Kotlin team. javac never issues such stack map frames and a lot of tool struggle with such "special handling" as you cannot really enhance a method or use agents on them as most people expect it.

**Comment by elizarov** [comment] 2017-08-14 08:42
@raphw Here is the byte code that is produced by Kotlin compiler version 1.1.4-eap-69 for the `fetch` function. On this bytecode ByteBuddy complains with "java.lang.IllegalStateException: public final java.lang.Object SuspendableClass.fetch(boolean,kotlin.coroutines.experimental.Continuation) is inconsistent at 1: java/lang/Object". 

As you can see from the below bytecode, the boolean local variable 1 (update) is consistently manipulated as boolean type ('Z'). In fact, there are only two instructions ever touch it (at bci 104 and bci 129) to save/load into field of boolean (`Z`) type. Also, notice that all stack frames mention the proper type for local variable 1 (stack frame type `int`) and LocalVariableTable has its correct name and type. 

All in all, I don't see any miscomplication of this particular function by Kotlin compiler.

```
  public final java.lang.Object fetch(boolean, kotlin.coroutines.experimental.Continuation<? super java.lang.Integer>);
    descriptor: (ZLkotlin/coroutines/experimental/Continuation;)Ljava/lang/Object;
    flags: ACC_PUBLIC, ACC_FINAL
    Code:
      stack=4, locals=6, args_size=3
         0: aload_2
         1: instanceof    #10                 // class SuspendableClass$fetch$1
         4: ifeq          36
         7: aload_2
         8: checkcast     #10                 // class SuspendableClass$fetch$1
        11: astore_2
        12: aload_2
        13: invokevirtual #14                 // Method SuspendableClass$fetch$1.getLabel:()I
        16: ldc           #15                 // int -2147483648
        18: iand
        19: ifeq          36
        22: aload_2
        23: dup
        24: invokevirtual #14                 // Method SuspendableClass$fetch$1.getLabel:()I
        27: ldc           #15                 // int -2147483648
        29: isub
        30: invokevirtual #19                 // Method SuspendableClass$fetch$1.setLabel:(I)V
        33: goto          46
        36: new           #10                 // class SuspendableClass$fetch$1
        39: dup
        40: aload_0
        41: aload_2
        42: invokespecial #23                 // Method SuspendableClass$fetch$1."<init>":(LSuspendableClass;Lkotlin/coroutines/experimental/Continuation;)V
        45: astore_2
        46: aload_2
        47: getfield      #27                 // Field SuspendableClass$fetch$1.data:Ljava/lang/Object;
        50: astore_3
        51: aload_2
        52: getfield      #31                 // Field SuspendableClass$fetch$1.exception:Ljava/lang/Throwable;
        55: astore        4
        57: invokestatic  #37                 // Method kotlin/coroutines/experimental/intrinsics/IntrinsicsKt.getCOROUTINE_SUSPENDED:()Ljava/lang/Object;
        60: astore        5
        62: aload_2
        63: invokevirtual #14                 // Method SuspendableClass$fetch$1.getLabel:()I
        66: tableswitch   { // 0 to 1
                       0: 88
                       1: 125
                 default: 153
            }
        88: aload         4
        90: dup
        91: ifnull        95
        94: athrow
        95: pop
        96: aload_0
        97: aload_2
        98: aload_2
        99: aload_0
       100: putfield      #40                 // Field SuspendableClass$fetch$1.L$0:Ljava/lang/Object;
       103: aload_2
       104: iload_1
       105: putfield      #44                 // Field SuspendableClass$fetch$1.Z$0:Z
       108: aload_2
       109: iconst_1
       110: invokevirtual #19                 // Method SuspendableClass$fetch$1.setLabel:(I)V
       113: invokevirtual #48                 // Method fetchConcrete:(Lkotlin/coroutines/experimental/Continuation;)Ljava/lang/Object;
       116: dup
       117: aload         5
       119: if_acmpne     147
       122: aload         5
       124: areturn
       125: aload_2
       126: getfield      #44                 // Field SuspendableClass$fetch$1.Z$0:Z
       129: istore_1
       130: aload_2
       131: getfield      #40                 // Field SuspendableClass$fetch$1.L$0:Ljava/lang/Object;
       134: checkcast     #2                  // class SuspendableClass
       137: astore_0
       138: aload         4
       140: dup
       141: ifnull        145
       144: athrow
       145: pop
       146: aload_3
       147: pop
       148: iconst_2
       149: invokestatic  #54                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
       152: areturn
       153: new           #56                 // class java/lang/IllegalStateException
       156: dup
       157: ldc           #58                 // String call to 'resume' before 'invoke' with coroutine
       159: invokespecial #61                 // Method java/lang/IllegalStateException."<init>":(Ljava/lang/String;)V
       162: athrow
   LocalVariableTable:
        Start  Length  Slot  Name   Signature
           96      57     0  this   LSuspendableClass;
           96      57     1 updateOnly   Z
           96      57     2 continuation   Lkotlin/coroutines/experimental/Continuation;
      LineNumberTable:
        line 3: 60
        line 4: 96
        line 3: 122
        line 5: 147
      StackMapTable: number_of_entries = 8
        frame_type = 255 /* full_frame */
          offset_delta = 36
          locals = [ class SuspendableClass, int, class java/lang/Object ]
          stack = []
        frame_type = 255 /* full_frame */
          offset_delta = 9
          locals = [ class SuspendableClass, int, class SuspendableClass$fetch$1 ]
          stack = []
        frame_type = 254 /* append */
          offset_delta = 41
          locals = [ class java/lang/Object, class java/lang/Throwable, class java/lang/Object ]
        frame_type = 70 /* same_locals_1_stack_item */
          stack = [ class java/lang/Throwable ]
        frame_type = 29 /* same */
        frame_type = 83 /* same_locals_1_stack_item */
          stack = [ class java/lang/Throwable ]
        frame_type = 65 /* same_locals_1_stack_item */
          stack = [ class java/lang/Object ]
        frame_type = 5 /* same */
```

**Comment by elizarov** [comment] 2017-08-14 10:07
A few other comments. It reproduces with a simpler code. You don't need a `boolean` parameters. It fails with a parameter-less function, too. I've put a reproducer code into this project: 
https://github.com/elizarov/CoroutinesMockitoPlayground
You can check it out to confirm the problem. The simpler reproducer code is here:
https://github.com/elizarov/CoroutinesMockitoPlayground/blob/master/src/main/kotlin/SuspendableClass.kt
The test case is here:
https://github.com/elizarov/CoroutinesMockitoPlayground/blob/master/src/test/kotlin/SuspendableClassTest.kt

Running this test case produces the following cause of the failure to mock this class which comes from ByteBuddy:
```
java.lang.IllegalStateException: public final java.lang.Object SuspendableClass.fetch(kotlin.coroutines.experimental.Continuation) is inconsistent at 0: java/lang/Object
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1200)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1141)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:6636)
	at net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2910)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1628)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:167)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:117)
	... 45 more
```

**Comment by elizarov** [comment] 2017-08-15 16:13
@raphw I _think_ I understand what's going there. See, the first full-frame that is emitted by Kotlin compiler:

```
StackMapTable: number_of_entries = 8
        frame_type = 255 /* full_frame */
          offset_delta = 36
          locals = [ class SuspendableClass, int, class java/lang/Object ]
          stack = []
```

It declares that local variable 2 is of class `java.lang.Object`. However, the actual parameter to the method that will fall into this local variable is of class `kotlin.coroutines.experimental.Continuation`. It is a perfectly legal from the standpoint of JVM specification, since `Continuation` is a subclass of `Object`. However, ByteBuddy contains the following check at  https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L4008

```
if (!toFrame(methodDescription.getParameters().get(index).getType().asErasure()).equals(localVariable[index + offset])) { ...
```
 
that basically requires that frame type is equal to parameter type, which is a stronger requirement than mandated by JVM specification.

I've build a custom version of ByteBuddy with this check commented out (I'd really see any value in it, just a too strict/defensive constraint). With this custom version of ByteBuddy, mockito test for final Kotlin suspending function passes.

**Comment by elizarov** [comment] 2017-08-15 16:21
This is a pull request with a fix to mockito: https://github.com/raphw/byte-buddy/pull/332

**Comment by elizarov** [comment] 2017-08-15 16:26
This a pull request with the corresponding mockito test https://github.com/mockito/mockito/pull/1165

**Comment by raphw** [comment] 2017-08-15 21:44
I had time to look at it now and you are right about the problem. Your solution does however not work, the problem goes a bit deeper.

We need to be able to access the arguments after the original code was added. The inline mock maker basically takes a method:

```java
void foo(String a) {
  // code here
}
```
and transforms it to:
```java
void foo(String a) {
  // Mockito code start
  if (someCriteria) {
    // code here
  }
  // Mockito code end
}
```
Where Mockito code is added at the end, we still need to be able to dereference the original arguments what is no longer possible about passing the full frame if the first argument was for example rendered to be an `Object`. Of course, this is allowed by the spec but it is highly uncommon. `javac` does not do it, `scalac` does not do it and most runtime tools (Javassist, Byte Buddy) cannot work with such a limitation.

As a workaround, I considered to make a copy of the original argument values in a dedicated index range but it is a bit costly and can break for methods that already have a large number of arguments. I would need to spend some time to implement this feature and I am not sure if I like the solution either.

Is there a particular reason that Kotlin even touches the argument indices?

**Comment by elizarov** [comment] 2017-08-16 09:11
@raphw Let me add some additional observations here:

* If there is a goal to determine _original_ arguments at the end of the method, then they _must_ be stored to separate local variables at the beginning of the method. To see why, try instrumenting this java method and check what arguments ByteBuddy sees when the method exits:

```
void foo(String a) {
    a = "Ha, ha!";
}
```

* The `Continuation` parameter that is the cause of the problem here is not the actual parameter in Kotlin. It is not present in function's declaration nor on its call site. It is fully synthetic. Note, that in order to support Kotlin's suspending functions Mockito was also modified to ignore this parameter, so it is never going to be looked at it in any way by Mockito.

* This particular frame (at bci 36) has `Object` type for this continuation parameter as an artifact of ASM's frame computation logic. In fact, Kotlin always stores an object that is an instance of `Continuation` into this local variable, but, somehow, when computing the frames, the `Object` type is derived as LCA at this bytecode offset. We can fix this particular full frame (at bci 36), but ByteBuddy check will still fail at the next full frame (at bci 46), because it declares that this local variable now has a type of class `SuspendableClass$fetch$1`. It is an instance of `Continuation`, too. However, this more specific frame information is now critical to the subsequent logic of the compiled code, because we need to spill coroutine state into that object before suspending and it must be of this more specific type in order for the subsequent code to be verifiable. So we cannot really fix it in any satisfactory manner, but by saving a copy of the original parameter for ByteBuddy's pleasure, which is counter-intitive, since if ByteBuddy want to use the original parameters, then it should have been taking care to save those parameters itself (see the Java example in the beginning).

Having said all of the above, compilation of suspending functions in Kotlin is under a constant enhancement now and will be changed several more times in the future releases. One of the future changes might or might not remove this particular effect that is causing a problem with ByteBuddy. I still believe, though, that ByteBuddy should save original parameters if it cares about them at the method's exit.

**Comment by raphw** [comment] 2017-08-16 10:17
This would not be a problem in our case as the above method could be transformed into something like:
```
void foo(String a) {
  if (notAMockCall) {
    a = "Ha, ha!";
  } else {
    // full stack frame with (this, String)
    // our logic
  }
}`
```
If our code is reached and we access the arguments, we can tell that the actual code was guarded by a conditional and they were not altered. The problem with stack map frames is that they are not conditional. If the guarded code contains a stack map frame that overrides the argument types, we can no longer access them even if the guarded code was never run.

I am aware of this being an assumption but despite Kotlin, no popular compiler for a JVM language overrides the indices that describe the method arguments. To overcome this limitation, Byte Buddy needs to be extended and I hope to do this sometime in the future but for the close future, I will not find time to do so.

As a general advice, I find it however advisable to stay as close to javac-compatible byte code as possible as many tools out there are based on such assumptions, simply because they work 99.99% of the time and a lot of Java agents rely on this. The original choice for this solution is also based on byte code efficiency as extending (large) methods too much costs significant runtime and can tip over the JIT compiler. There are always tradeoffs to consider.

**Comment by elizarov** [comment] 2017-08-16 12:26
@raphw Notice, that the problematic frame in question is in the middle of the method body, so the transformation you've described above is not going to cause any problems. See:

```
void foo(String a) {
  if (notAMockCall) {
    // somewhere in the middle of the body we are redefining local variable with different type
    // it is Ok, because we are not going to go into an else branch with a modified frame
  } else {
    // original stack frame implied by parameters
    // our logic
  }
}
```

Kotlin compiler is not redefining the (implicit) stack frame that every method has at its beginning. So, the transformation that mockito is doing with ByteBuddy using is 100% safe. Moreover, I did actually check that the resulting code (with a patched version of ByteBuddy without the check) not only passes verification, but works as expected.

All in all, I don't see any reason to have a strict check on stack frames declared somewhere in the middle of method's bytecode.

Answering your other question, Kotlin compiler does use ASM to compute stack frames.

**Comment by raphw** [comment] 2017-08-16 12:57
Byte Buddy offers access to arguments according to the signature of
> LSuspendableClass;ILkotlin/coroutines/experimental/Continuation;
whereas the state after the available frames becomes
> LSuspendableClass;ILjava/lang/Object;
The way that Byte Buddy advice works is by inlining precompiled byte code into an existing method and for this purpose, it validates that the above signature of the initial arguments is still intact even if the code is never executed as the verifier might complain.

It is true that this works out without the security check in this case as Byte Buddy collects all arguments into an object array but if you did for example replace the third frame with a primitive value or delete it alltogether, this would no longer be possible if such a stack map frame was issued in non-reached code. The verifier does not apply any dynamic analysis here, it only checks if the stack map frame that is expected matches the current state from top to bottom of the method.

As I said, Byte Buddy could be smarter here by analyzing byte code on the fly but stack map frame analysis at runtime is a very tricky business as so many frameworks like Spring rely on optional types where ASM's stack map frame feature would fail, too. Therefore, Byte Buddy relies on the consistency of the stack map frames for the original arguments or aborts the transformation.

In the future, I hope to add another mode where this form of stack map frame pattern is supported or where Byte Buddy makes a copy of all references what would probably be the most correct. It is however not done by removing the check which is important to avoid verification errors which Byte Buddy implicitly promises to avoid.

This is on my list of things to do but nowhere in the near future as I currently prioritize Java 9 compatibility. I will keep you posted once I update this.

PS: why don't you issue the stack map frames yourself? You should have the necessary information in your compiler anyways and the inferred computation by ASM is rather expensive and sometimes error prone.

**Comment by elizarov** [comment] 2017-08-16 14:43
@raphw It is just easier to do it with ASM and it is fast for us due to the way `getCommonSuperClass ` is defined to always return `Object` (it is a Kotlin-specific optimization, you cannot do this trick on a general bytecode), so it converges quickly.
 
I see that ByteBuddy supports `Advice.OnMethodExit` with `Advice.Argument`. However, it means that it must save the original argument value on the method entry anyway, or it will no longer be equal the original argument value on method exit. 

Anyway, notice that Mockito does not use `Advice.Argument` with `Advice.OnMethodExit`. So, as a quick solution for Mockito, can we, please, change this check, so that it requires exact stack frames in the middle of the method only when `Advice.OnMethodExit` has at least one `Advice.Argument` parameter and avoid/remove this check otherwise?

**Comment by raphw** [comment] 2017-08-23 15:41
I have a solution drafted out that does not increase the amout of byte codes. Hope to complete it by the end of September.

**Comment by elizarov** [comment] 2017-08-30 11:20
The bytecode generation strategy was adjusted in Kotlin 1.1.4-3 which fixes this issue. See [KT-19713](https://youtrack.jetbrains.com/issue/KT-19713) for details. I've updated PR #1165 with the test for this issue to Kotlin 1.1.4-3 and it passes. I suggest to close this issue and to merge PR #1162 into Mockito codebase to increase test coverage.

**Comment by TimvdLippe** [comment] 2017-11-04 16:31
Closing per above comment. Thanks for the effort and extra explanation @elizarov !

**Closed by TimvdLippe** 2017-11-04 16:31 UTC

**Comment by sinwe** [comment] 2018-03-26 19:38
I'm getting this again with 2.17.0. It works with 2.16.0

**Comment by TimvdLippe** [comment] 2018-03-26 19:40
@raphw @elizarov Hm, this might be a regression between Kotlin and Bytebuddy?

**Comment by sinwe** [comment] 2018-03-26 19:43
@TimvdLippe Sorry, I forgot to mentioned that I don't use Kotlin, but I'm using scala

**Comment by sinwe** [comment] 2018-03-26 20:04
Just to give update, I think it is related to bytebuddy 1.8.0. I force mockito 2.17.0 to use bytebuddy 1.7.9 and it works properly.

**Comment by raphw** [comment] 2018-03-27 08:04
I will look into this, I did a complete rework of the stack map frame handling but I assume there is a regression somewhere. The idea is that this should no longer be a problem alltogether.

This rewrite was really complex and its impossible to catch everything. Could you do me a favor and try with Byte Buddy built from master? I already fixed a few bugs I was made aware of. I wonder if the one you noticed is related.

Thanks for your help!

**Comment by sinwe** [comment] 2018-03-27 13:41
How can I get Byte Buddy from master?

**Comment by raphw** [comment] 2018-03-27 15:13
Check it out from GitHub and build it with Maven locally.

**Comment by sinwe** [comment] 2018-03-27 15:36
The master failed to build?
[![Build Status](https://travis-ci.org/raphw/byte-buddy.svg?branch=master)](https://travis-ci.org/raphw/byte-buddy)

**Comment by odin-delrio** [comment] 2018-04-10 00:06
@sinwe maybe is not your case, but I found this issue by searching in google... so this comment could be helpful for somebody else:

In my case, errors started after installing JAVA 10 in my laptop.
Switching back to JAVA 8 made mockito working as expected again.

(I'm using kotlin).

**Comment by sinwe** [comment] 2018-04-12 18:39
@raphw, I tried to use master and it is passing for me.
