### ISSUE TITLE
Documentation:  Don't mock types you don't own!

### ISSUE THREAD

**Issue by tpd-opitz** [mockito/mockito#1266] opened 2017-11-21 13:12 UTC
I'd say the "Don't mock type you don't own!" is the false conclusion out of the right reasoning.

Unittests should only need to be changes if *your API* changes or the part of an API of a dependency *your code uses*.
#### example:

>    You us an interface of a dependency as an input parameter, but your tested code uses only one method in that interface. If you don't mock this interface (which is a type you don't own) you have to create your own dummy implementation implementing all of the interfaces methods, even those you don't use.

>    If you change the version of that dependency this interface might have additional method and/or some methods have been removed. You have to change all of your the implementations of this interface throughout your program. If you mocked this interface you don't need to change your tests and they still give you confidence that your codes behavior did not change after the required refactoring.

Furthermore your Unittest should only fail because the behavior of *your code* changed, not because of a change in the dependencies behavior. Changes in a dependencies behavior should be pinned with separate Unittest you setup for the dependencies behavior and/or *integration tests*.

**Comment by bric3** [comment] 2017-11-21 14:30
> Changes in a dependencies behavior should be pinned with separate Unittest you setup for the dependencies behavior and/or integration tests.

In practice nobody does that. 

> Furthermore your Unittest should only fail because the behavior of your code changed, not because of a change in the dependencies behavior.

That's precisely the point, with mocks the unit tests won't fail, while the third party library or the JVM, changed in behavior.

**Comment by tpd-opitz** [comment] 2017-11-21 17:48
> In practice nobody does that.

Sure, because it is quite unlikely that dependencies change in a way that affects the correctness of my application. This is at least my experience in 15+ years Java development.

> That's precisely the point, with mocks the unit tests won't fail, while the third party library or the JVM, changed in behavior.

I argee.

But I argue that this is a bad thing.

**Comment by TimvdLippe** [comment] 2019-04-30 15:56
I am closing this issue as working as intended. I am open for future discussion of course, but for now we want to make developers more cautious about mocking rather than encouraging more mocking.

**Closed by TimvdLippe** 2019-04-30 15:56 UTC
Labels: docs
