### ISSUE TITLE
OSGI bundle for org.mockito.junit.jupiter

### ISSUE THREAD

**Issue by stbischof** [mockito/mockito#2144] opened 2020-12-14 17:44 UTC
Could you please pack the artifact ''org.mockito:mockito-junit-jupiter:jar' as an osgi-bundle?

**Comment by TimvdLippe** [comment] 2020-12-14 18:21
Sounds good, do you mind to open a PR?

**Comment by TimvdLippe** [comment] 2021-01-04 12:54
Duplicate of #1997

**Closed by TimvdLippe** 2021-01-04 12:54 UTC
Labels: please contribute
