### ISSUE TITLE
Mockito development does not contain versions from 3.3.9 to up

### ISSUE THREAD

**Issue by danielgomezrico** [mockito/mockito#1963] opened 2020-07-03 02:36 UTC
Bintray deploys show shows that there are 3.3.13 version deployed but it is not in the maven repository

Check https://dl.bintray.com/mockito/maven/org/mockito/mockito-core/ 

It just includes versions until 3.3.9.

Maybe something went wrong in the deploy process?

**Comment by TimvdLippe** [comment] 2020-07-03 15:31
Duplicate of #1738

**Closed by TimvdLippe** 2020-07-03 15:31 UTC
