### ISSUE TITLE
Regression with JDK-9-ea+104 and Mockito 2.0.42-beta

### ISSUE THREAD

**Issue by cushon** [mockito/mockito#355] opened 2016-02-14 21:00 UTC
The stack trace looks the same as #272, but it's happening with a recent JDK-9-ea release and the 2.0.42 beta.

Tested with:

```
$ java -fullversion
java full version "9-ea+104-2016-02-03-193932.javare.4385.nc"
```

Repro:

```java
import org.mockito.Mockito;
import org.junit.Test;

public class DemoTest {
  @Test public void test() {
    Mockito.mock(Object.class);
  }
}
```

```
JUnit version 4.12
.E
Time: 0.041
There was 1 failure:
1) test(DemoTest)
java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:35)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:13)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:12)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
	at org.mockito.Mockito.<clinit>(Mockito.java:1103)
	at DemoTest.test(DemoTest.java:6)
	...
Caused by: java.lang.NullPointerException
	at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:18)
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 39 more
```

**Comment by raphw** [comment] 2016-02-15 08:52
This is not related to #272 (As of today, Byte Buddy still implements special handling for JDK 9 which does not yet use version 9 byte code, this changes once the ea-builds increment their byte code version).

This might be some initialization circularity, I cannot really see how the NPE is happening here.

**Comment by cushon** [comment] 2016-02-15 09:38
It was a non-jigsaw build on OS X, but I see the same crash with jigsaw builds and on other platforms.

**Comment by MGaetan89** [comment] 2016-03-08 13:30
I have the same issue on Ubuntu 15.10, using Java 7 and Mockito 2.0.43-beta:

```
$ java -fullversion
java full version "1.7.0_40-b43"
```

```
java.lang.ExceptionInInitializerError
at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:35)
at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:13)
at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:12)
at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:28)
at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
at org.mockito.Mockito.<clinit>(Mockito.java:1103)
at com.myApp.MyFragmentTest.before(MyFragmentTest.java:41)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.mockito.plugins.StackTraceCleanerProvider org.mockito.internal.configuration.plugins.PluginRegistry.getStackTraceCleanerProvider()' on a null object reference
at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:18)
at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
... 50 more
```

**Comment by bric3** [comment] 2016-03-08 13:38
@MGaetan89 Not the same apparently the cause seems different, do you have a code sample that reproduces your issue. Are you working on some Android project ?

**Comment by MGaetan89** [comment] 2016-03-08 13:54
Yes, I am using Mockito in an Android project. I will try to provide a minimal sample code.
My test was working while it was in the `test` folder (basic unit test), and I got this exception when I moved it to the `androidTest` folder.

The code that fails is in a `@Before` method and looks like this (it is a `Parameterized` test):

```java
// The test class has a field named 'fragment'
this.fragment = spy(new MyFragmentTest()); // The exception happens here (or anywhere Mockito is called for the first time, if I remove the 'spy' call)
doNothing().when(this.fragment).method1();
doNothing().when(this.fragment).method2();
doNothing().when(this.fragment).method3();
```

**Comment by bric3** [comment] 2016-03-08 13:59
@MGaetan89 There's nothing wrong in the snippet there. It could be something else outside the reach of mockito, like a classpath issue or maybe incompatibilities with some Android toolchain. I would check that first, un fortunately I'm not an Android dev, so I cannot help much on this front.

**Comment by thekingnothing** [comment] 2016-03-08 14:14
FYI, two bugs was recently created for PowerMock with same stack trace. 
https://github.com/jayway/powermock/issues/634
As you may see Mockito 1.10.19 is used. I think that it could be an issue with class loaders or new version of JDK. I'm going to check issue with previous versions.

**Comment by bric3** [comment] 2016-03-08 17:58
Android toolchain upgrade ?
There may be something that don't work with the way mockito loads his own extensions, this is the time to debug [`PluginLoader`](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/internal/configuration/plugins/PluginLoader.java) or classes that uses it to load for exemple the stack trace cleaner.

**Comment by thekingnothing** [comment] 2016-03-08 19:02
@bric3, did you ask me? 

Anyway, thanks for the tip, I'll debug `PluginLoader`

**Comment by bric3** [comment] 2016-03-09 12:27
Nope thinking out loudly ;)

**Comment by PascalSchumacher** [comment] 2016-06-19 15:57
The test from #304 passes on current master d648014 so maybe this issue is also solved?

**Comment by raphw** [comment] 2016-07-01 15:14
I am closing this issue in an attempt to clean up as this issue seems resolved.

**Closed by raphw** 2016-07-01 15:14 UTC
Labels: android, java-9, ready
