### ISSUE TITLE
Conflict with dependency 'org.mockito:mockito-core'

### ISSUE THREAD

**Issue by nikiJava** [mockito/mockito#739] opened 2016-11-04 15:54 UTC
Have a problem with mockito's depenndencies:

:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
Conflict with dependency 'net.bytebuddy:byte-buddy'. Resolved versions for app (1.4.3) and test app (1.5.3) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Conflict with dependency 'org.mockito:mockito-core'. Resolved versions for app (2.0.71-beta) and test app (2.2.11) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:prepareDebugUnitTestDependencies'.
> Dependency Error. See console for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

From my build.gradle:
testCompile 'org.mockito:mockito-core:2.2.11'

**Comment by bric3** [comment] 2016-11-04 16:11
Hi,

I don't think mockito distribution is in cause there, instead I think the issue is rather in the tool chain. For instance it is known that some android libraries are not yet updated to support mockito 2 yet like dexmaker.

I don't know what `:app:prepareDebugUnitTestDependencies` task, but I would definitely start investigating here.

**Comment by TimvdLippe** [comment] 2016-12-23 00:33
Closing this issue as it does not appear to be an issue with Mockito. Please reply with more information if this remains an issue related to Mockito.

**Closed by TimvdLippe** 2016-12-23 00:33 UTC
Labels: android, awaiting response, question
