### ISSUE TITLE
InjectMocks is wrongly injecting the same Mock into 2 different fields of similar type despite creating 2 different mocks.

### ISSUE THREAD

**Issue by Meaaow** [mockito/mockito#2041] opened 2020-09-14 17:44 UTC
> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : http://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

I have a class which has 2 fields of similar types. I have mocked them both. But when I use InjectMocks, inject mocks wrongly injects a single mock into both those fields.

Here is the example code class:

```

import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;

import java.util.Set;
import java.util.function.Consumer;

@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class TestClass {

    private final Consumer<Set<Integer>> intConsumer;

    private final Consumer<Set<String>> stringConsumer;

    void PrintClass(){
        System.out.println("intConsumers: " + intConsumer);
        System.out.println("stringConsumers: " + stringConsumer);
    }
}
```

Here is the test class:

```

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Set;
import java.util.function.Consumer;

@RunWith(MockitoJUnitRunner.class)
public class TestClassTest {

    @Mock private Consumer<Set<Integer>> intConsumer;
    @Mock private Consumer<Set<String>> stringConsumer;
    @InjectMocks private TestClass testClass;

    @Test
    public void testPrint(){
        testClass.PrintClass();
    }


}

```

Here is the output when I run the test : testPrint(): intConsumer is injected into both intConsumer and stringConsumer.

```
intConsumers: intConsumer
stringConsumers: intConsumer



Process finished with exit code 0
```

I am using Maven. 
```
<dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>2.7.19</version>
</dependency>
```

**Comment by TimvdLippe** [comment] 2021-01-19 00:06
Duplicate of #1066

**Closed by TimvdLippe** 2021-01-19 00:06 UTC
