### ISSUE TITLE
ReflectionMemberAccessor: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by hyperhunt** [mockito/mockito#2146] opened 2020-12-16 14:41 UTC
How to fix it?
    
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.ReflectionMemberAccessor (file:/home/tony/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/3.6.28/ad16f503916da658bd7b805816ae3b296f3eea4c/mockito-core-3.6.28.jar) to field java.util.LinkedList.size
WARNING: Please consider reporting this to the maintainers of org.mockito.internal.util.reflection.ReflectionMemberAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Code
```
    @Test
    fun testSpyWrong() {
        val list: List<String> = LinkedList()
        val spy: List<String> = spy(list)
        doReturn("HelloSpy").`when`(spy)[0]
        assertEquals(spy[0], "HelloSpy")
    }
```

Gradle
```
id 'org.jetbrains.kotlin.jvm' version '1.4.21'

implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
testImplementation("org.mockito:mockito-core:3.6.28")
```

**Comment by TimvdLippe** [comment] 2020-12-16 14:51
Duplicate of #1325

**Closed by TimvdLippe** 2020-12-16 14:51 UTC
