### ISSUE TITLE
Maven distribution mockito-core-1.10.16.jar contains *.java files (should only contain *.class files)

### ISSUE THREAD

**Issue by jborgland** [mockito/mockito#199] opened 2015-04-16 12:05 UTC
This bug seems to be still present (in all versions that I have checked):
https://code.google.com/p/mockito/issues/detail?id=418

Simply pasting in the bug description from the old bug below.

**What steps will reproduce the problem?**
1. Include the following standard dependency in pom.xml:
```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>1.9.5</version>
    <scope>test</scope>
</dependency>
```
 
2. Run the command: 
   `mvn install`
   to ensure the dependencies are downloaded to the local repository (in ~/.m2/repository)

3. Run the command:
    `jar tvf ~/.m2/repository/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar`

**What is the expected output? What do you see instead?**

Expected output is a list of *.class files.

Actual output is a list of both *.class and *.java files.

The *.java files appear correctly in the mockito-core-1.9.5-sources.jar file (when downloaded by Maven), but should not appear in the mockito-core-1.9.5.jar file.

**What version of the product are you using? On what operating system?**

Mockito 1.9.5, Ubuntu Linux (although this problem is not specific to any operating system).

**Comment by bric3** [comment] 2015-04-16 17:35
For reference there this ticket also #158

**Comment by jborgland** [comment] 2015-06-04 19:08
Additional note:

This currently causes a bunch of javadoc warnings in our builds that I can't figure out how to get rid of (without suppressing other things that I'd like to keep):

[javadoc] javadoc: warning - Multiple sources of package comments found for package "org.mockito"
[javadoc] javadoc: warning - Multiple sources of package comments found for package "org.mockito.invocation"
[javadoc] javadoc: warning - Multiple sources of package comments found for package "org.mockito.stubbing"

**Comment by bric3** [comment] 2015-06-05 09:51
@jborgland Isn't it related to the `Xdoclint` flag ? The gradle javadoc task is `mockitoJavadoc` and disables it.

For reference check this entry of Stephen Colebourne : http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by szczepiq** [comment] 2015-10-10 18:20
I'm going to close this ticket as this references Mockito 1.10 which is an old release (we're working on 2.x)

**Comment by szczepiq** [comment] 2015-10-10 18:20
The issue is reported very cleanly and elegantly. Thanks a lot and keep them coming! This is very helpful.

**Closed by szczepiq** 2015-10-10 18:20 UTC
