### ISSUE TITLE
Use JDK 7 with Java 6 compatibility for building release artifacts

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#1020] opened 2017-04-03 16:00 UTC
We need community feedback if it is ok to change the JDK we use to build release artifacts for mockito. 

###  Problem

Currently Mockito is build on JDK 6. This ensures it will work with Java 6. However, this causes issues like "sun.security.validator.ValidatorException: PKIX path building failed" (https://github.com/mockito/mockito-release-tools/issues/60). This issues makes it problematic for us to setup up continuous delivery automation with Travis CI and Gradle.

### Question

Is ok to start building release artifacts of Mockito 2.x with JDK 7 (with Java 6 compatibility)? This will help with release automation and also is safer because Java 6 is no longer supported by Oracle.

Thank you in advance for answers!

**Comment by TimvdLippe** [comment] 2017-04-03 16:05
This would be a major breaking change, so I am not for this. Can we contact Travis to investigate what the issue is?

**Comment by szczepiq** [comment] 2017-04-04 13:50
Why would this be a breaking change? We would compile with Java 6 compatibility and generate bytecode that works on Java 6.

**Comment by TimvdLippe** [comment] 2017-04-04 21:29
Ah, I misunderstood. So we build on JDK7, but set it to be Java 6 compatibility. Afaik, Gradle does not complain about Java 6 incompatible changes on newer JDKs, but the risk is probably low.

Could we maybe remove the release tool from the JDK6 Travis build, thus releasing on JDK7, but still build on JDK6 on Travis too?

**Comment by szpak** [comment] 2017-04-04 21:33
@TimvdLippe https://github.com/xvik/gradle-animalsniffer-plugin can be use to detect constructions not compatible with Java 6.

**Comment by TimvdLippe** [comment] 2017-04-04 21:41
@szpak Ah cool, TIL! Yes then let's go ahead and adopt that plugin + switch to JDK7

**Comment by szpak** [comment] 2017-04-04 21:53
I will add that plugin in 2.x branch as a preparation to the switch.

**Comment by szczepiq** [comment] 2017-04-05 06:55
@szpak, animalsniffer looks interesting! Why do we need animal sniffer given that we can compile on JDK7 with **source** and **target** compatibility set to 1.6?

**Comment by TimvdLippe** [comment] 2017-04-05 07:02
Because these are actually not checked. See the recent PR of the diamond generic which locally had not installed the jdk6

**Comment by TimvdLippe** [comment] 2017-04-05 07:03
See this specific comment: https://github.com/mockito/mockito/pull/1014#issuecomment-290741441

**Comment by szpak** [comment] 2017-04-05 07:38
@szczepiq Source/target version result in byte code to be in the correct version/format. It doesn't check if given construction (e.g. a method) was available in a given JDK version.

**Comment by szpak** [comment] 2017-04-05 08:34
E.g. `Objects.isNull("aa");` builds fine with Java 7+ in Mockito (without AnimalSniffer). Created #1021.

**Comment by szczepiq** [comment] 2017-04-05 14:02
@szpak, thank you this makes perfect sense! I thought that Java is smarter :)

@TimvdLippe, diamond is detect and flagged when we use sourceCompatibility = 1.6. That's the whole point of the 'sourceCompatibility' setting. The reason it was not detected in the PR you mentioned is that the PR changed the code in extTest and that code is test code without configured source compatibility (it does not have to, it is not code that we ship to the client).

I'm not in favor of introducing animal sniffer plugin. I'd rather keep things simple and just run builds on Java6. Extra plugins / dependencies are stuff we have to maintain.

**Comment by bric3** [comment] 2017-04-05 14:46
The sooner we drop java 6/7 the better. It delays our work on mockito 3 for Java 8 / 9.

**Comment by szpak** [comment] 2017-04-06 15:33
@szczepiq As an alternative you can [try](https://docs.gradle.org/3.5-rc-3/userguide/java_plugin.html#sec:java_cross_compilation) to use Java 6 to only compile code while Gradle is executed with Java 7. It would also allow to use newer Gradle in 2.x branch.

**Comment by szpak** [comment] 2017-04-12 07:50
Closing as we switched to JDK7 build in #1021.

**Closed by szpak** 2017-04-12 07:50 UTC
Labels: feedback-needed
