### ISSUE TITLE
Mockito can't spy on object loaded in parent classloader

### ISSUE THREAD

**Issue by akomisarek** [mockito/mockito#133] opened 2014-12-10 19:57 UTC
I have encountered issue with Mockito (I have tested this on 1.10.14) and usage of different classloaders - running tests in SBT 0,13.

I have got empty class *TestClass* and following test:
```Java
    @Test
    public void runTest() {
        Mockito.spy(new TestClass(){

        });
    }
```
This test fails with following: 
```
Caused by: org.mockito.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
[error]     at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:238)
[error]     at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
[error]     at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
[error]     at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
[error]     at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
[error]     at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
[error]     at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
[error]     at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
[error]     at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
[error]     at org.mockito.Mockito.spy(Mockito.java:1367)
[error]     ... 56 more
[error] Caused by: java.lang.reflect.InvocationTargetException
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:606)
[error]     at org.mockito.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:385)
[error]     at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:220)
[error]     ... 65 more
[error] Caused by: java.lang.IllegalAccessError: class TestMock$1$$EnhancerByMockitoWithCGLIB$$7c797c20 cannot access its superclass TestMock$1
[error]     at java.lang.ClassLoader.defineClass1(Native Method)
[error]     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
```
Looks like there is class loader issue - in sbt, the default classloader is the one for the sbt launcher, but you are "run" in a sub classloader.

Following calls give different result: *Thread.currentThread().getContextClassLoader().getClass();* and *TestClass.class.getClassLoader().getClass();* 
The second one is the parent of the first one.

Of course there is no issue running this piece of code in IDE, but in my opinion this is Mockito's problem, something which could be improved. 
 
Is it possible to have this fixed in Mockito? I would say so because changing current classloader to the one used to load the class solves the issue.

**Comment by bric3** [comment] 2015-01-03 13:54
Play Framework users had a similar issue a while ago, now I know they are using SBT, it sometime ago but a workaround was to disable classcache in objenesis, maybe it can resolve your issue. We will be happy with the feedback.

This can be done easily with a configuration class that you can use in your test classpath. See the [`IMockitoConfiguration javadoc`](http://site.mockito.org/mockito/docs/current/org/mockito/configuration/IMockitoConfiguration.html)

Your implementation will have to always return `false` in this method [`enableClassCache()`](http://site.mockito.org/mockito/docs/current/org/mockito/configuration/IMockitoConfiguration.html#enableClassCache())

**Comment by akomisarek** [comment] 2015-01-19 20:43
@bric3 - thank you for potential suggestion, but unfortunately this doesn't change anything. I debugged the Mockito internals and there is simple issue with the classloader being passed to cglib library to create new Class. So the cache is not even working, because the classes are not loaded - so I believe it was different issue. 

For know I changed our code, but would like to see resolved at some point in the future.

**Comment by bric3** [comment] 2015-02-19 13:04
OK, note that CGLIB may very well be dropped in mockito 2, see this PR #171 
You could try that code and see if it works or if it could be improved. I have created a `ClassLoaders` test util to help class laoder testing, it may not be complete though.

**Comment by raphw** [comment] 2015-06-23 14:57
Should be fixed with using Byte Buddy's `MultipleParentClassLoader` but this is hard to reproduce. Would be great to test with the new beta.

**Comment by raphw** [comment] 2015-07-27 15:03
I have looked at this in further detail and this is difficult Java corner-case:

1. `TestClass` is an anonymous class which *javac* implements as a package-private class. In order to subclass such an anonymous class, one **must** load the subclass with the same class loader as the anonymous class.
2. The context of the class depends on different class loaders which requires using a `MultipleParentClassLoader` what breaks the first premise.

So to speak, package-private classes and multiple parent class loaders do not get well together.

As a bug fix, I suggest to:
1. Always mock anonymous classes as an anonymous class's super class / interface class.
2. Provide a better error message when a mock implicitly requires both (1) and (2).

**Comment by raphw** [comment] 2015-07-28 08:56
The problem is the following:

1. `TestClass` is an anonymous class which *javac* implements as a *package-private* class. In order to subclass such a package-private class, one must load the subclass with the same class loader as the anonymous class. Otherwise, the runtime package of the anonymous class is not visible to the mock class.

2. The test case implies dependencies on different class loaders which requires using a `MultipleParentClassLoader` what breaks the first premise.

I tried to fix this now by avoiding to use the actual package-private class. Strictly speaking, such an anonymous inner class does not render a type of its own, only an implementation. One could therefore strip the implemented type which is hopefully not package-private and instrument this public super type instead of the synthetic type that represents the anonymous class.

However, spies are implemented by delegating non-stubbed invocations to the *real* method **of the spy** and not of the instance spied upon. By not subclassing the anoymous class, any method implementations of the anonymous class would be lost. Similar to Java, Mockito binds an anoymous class's implementation to the implementation's type and it is non-trivial to detach them from each other.

I am afraid, this cannot be fixed without larger changes in Mockito's implementation.

**Comment by TimvdLippe** [comment] 2016-08-21 13:33
@raphw per above comment should we close this issue as wont-fix?

**Comment by bric3** [comment] 2016-08-22 12:38
For reference there's an answer that allows to delegate invocation to a concrete instance. 

```java
mock(TestClass.class, withSettings().defaultAnswer(AdditionalAnswers.delegatesTo(concrete)))
```

Maybe the issue is not there anymore as the mockmaker now uses the awesome features of bytebuddy as it also uses `MultipleParentClassLoader`.

**Comment by raphw** [comment] 2016-08-22 13:02
I removed the dependency to the context class loader; the problem still occurs however if a package-private class requires is loaded by another class loader as Mockito. I experienced with a few potential solutions, for example injecting dispatchers into the target class loader but it is all rather hacky. The problem has improvide for some classes using Mockito (e.g. no longer requiring the context class loader; but the problem is not really solvable on the JVM, unfortunately. I think we can close this as *won't fix*.

**Closed by raphw** 2016-08-22 13:02 UTC
Labels: bug, enhancement
