### ISSUE TITLE
@InjectMocks with option to indicate MockInjectionStrategies

### ISSUE THREAD

**Issue by jonathan-baudville** [mockito/mockito#2739] opened 2022-08-25 17:13 UTC
I have seen some issues injecting mocks in the target class when it contains both strategies constructor or field/method, I checked the logic in current classes and it seems to use one or the other, even if that is the default behavior what about having an option in the annotation to indicate the strategies.
ConstructorStrategy
ParameterStrategy
...
AllStrategies

For example, 
If there is a Service with dependencies by constructor  extending a BaseService with a @Autowired field/method dependency
```

BaseService {
   @Autowired BaseDependency baseDependency;
}

Service extends BaseService{
   final Dependency dependency
   Service (Dependency dependency){
      this.dependency = dependency
   }
}

Test {
   @Mock BaseDependency baseDependency;
   @Mock Dependency dependency;

   @InjectMocks (injectStrategy = AllStrategies)
   Service service;
   ...
}
```

**Comment by TimvdLippe** [comment] 2022-10-22 12:01
Duplicate of #2451

**Closed by TimvdLippe** 2022-10-22 12:01 UTC
