### ISSUE TITLE
Missing releases on Maven Central?

### ISSUE THREAD

**Issue by wilx** [mockito/mockito#2286] opened 2021-05-08 11:24 UTC
I am confused. I see releases like 3.9.10 here on GitHub but search.maven.org finds only [3.9.0](https://search.maven.org/artifact/org.mockito/mockito-core).

**Comment by TimvdLippe** [comment] 2021-05-08 11:26
Duplicate of #1738

**Closed by TimvdLippe** 2021-05-08 11:26 UTC
