### ISSUE TITLE
Incorrect parameter names in exception message for NPE when using mockito-inline

### ISSUE THREAD

**Issue by PBoddington** [mockito/mockito#2937] opened 2023-03-12 17:00 UTC
I am using Mockito version 5.2.0.

With `mockito-inline` the following code 

```
import static org.mockito.Mockito.mock;

public class MyClass {

  void method(long a, String b, String c) {
    b.hashCode();
  }

  public static void main(String[] args) {
    mock(MyClass.class);
    new MyClass().method(0, null, "C");
  }
}
```

throws an exception 
```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "c" is null
```

This message is incorrect as it is `b` that is `null`.

If you comment out the line `mock(MyClass.class);`, the exception message is correct.
The message is also correct if you use `mockito-subclass`.

**Comment by TimvdLippe** [comment] 2023-03-12 17:04
Duplicate of #2837

**Comment by PBoddington** [comment] 2023-03-12 17:05
@TimvdLippe It looks quite different to me. This issue is not specific to `hashCode.

**Comment by PBoddington** [comment] 2023-03-12 17:20
@TimvdLippe I've asked on StackOverflow https://stackoverflow.com/questions/75714954/bug-in-mockito-inline. This is a genuine but that needs to be fixed and nothing to do with the linked issue.

**Comment by TimvdLippe** [comment] 2023-03-12 17:28
Apologies for closing so quickly. I knew there were some shenanigans with hashcode and `mockito-inline`, so I assumed that was the case here again. @raphw any thoughts on this?

**Comment by PBoddington** [comment] 2023-03-12 17:30
No problem. Thank you for reopening!

**Comment by raphw** [comment] 2023-03-12 18:22
I'm not sure how the JVM extracts the variable name but it seems like an inconsistency in the meta data. I'll have a look.

**Comment by raphw** [comment] 2023-03-12 23:20
It's been an offset mapping issue in Byte Buddy which will be fixed with the next release.

**Comment by TimvdLippe** [comment] 2023-03-21 09:10
We updated our version of ByteBuddy, so this should now be fixed. Thanks Rafael!

**Closed by TimvdLippe** 2023-03-21 09:10 UTC
