### ISSUE TITLE
Support for @InjectMocks to inject already-created instances

### ISSUE THREAD

**Issue by sazzer** [mockito/mockito#1054] opened 2017-04-28 11:40 UTC
Disclosure - I'm doing this from Kotlin, where classes are final-by-default. That's part of the problem.

It would be very useful to have @InjectMocks able to inject fields that are already instantiated, but are not actually going to be managed by Mockito. Especially when these fields are of a final type and therefore can not be annotated with @Spy. As a very obvious example, `java.lang.String` comes to mind.

I envision something like a new @Injectable annotation that works the same as @Mock when it comes to injecting the value in via @InjectMocks, but that does no processing at all when it comes to initialising mocks. You could then do the following:

```
@RunWith(MockitoJUnitRunner.class)
public class SomeTest {
    @Mock
    private SomeInterface someInterface;

    @Injectable
    private String id = "ThisIsMyId";

    @InjectMocks
    private TestSubject testSubject;

    @Test
    public void test() {
        // At this point, Mockito has essentially executed:
        // someInterface = Mockito.mock(SomeInterface.class);
        // testSubject = new TestSubject(someInterface, id);
    }
}
```

**Comment by TimvdLippe** [comment] 2017-04-29 12:23
Closing this as a duplicate of #174. Please subscribe there for updates.

(note that we are hesitant to add this behavior, as we try to refrain making Mockito an injection framework).

**Closed by TimvdLippe** 2017-04-29 12:23 UTC
