### ISSUE TITLE
how to verify static method with void return called?

### ISSUE THREAD

**Issue by fqyuan** [mockito/mockito#2032] opened 2020-08-31 03:25 UTC
> I'm using mockito 3.5.7,  static method with non-void can work well. But how can i mock static void methd then?  I have searched to see powermockito has the ability to mock [this way](https://stackoverflow.com/questions/18466198/how-to-verify-static-void-method-has-been-called-with-power-mockito), does mockito support this feature? 
> I have turned to the [documentaion](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#48), but it has nothing to do with the static void method, any advice?
>

**Comment by TimvdLippe** [comment] 2020-09-04 14:00
Duplicate of #2027

**Closed by TimvdLippe** 2020-09-04 14:00 UTC
