### ISSUE TITLE
Source files should not be put in binary JAR 

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#157] opened 2015-01-15 12:36 UTC
Source files (`*.java`) should not be put into binary `mockito-core.jar`. It stupefies Idea to show decompiled file even when source jar is available.

**Comment by bric3** [comment] 2015-02-21 14:13
Duplicate of #28
Though the team thought it was better for project that don't rely on maven like source repositories.
cc @szczepiq

**Closed by bric3** 2015-02-21 14:13 UTC
