### ISSUE TITLE
Automated release notes generate duplicate entries

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#696] opened 2016-10-16 14:41 UTC
Currently the release notes generation creates duplicate entries in typical scenario: there is a ticket, it has corresponding PR, both of them are closed when PR is merged, release notes lists both as improvements. 

Proposed solution: Given that we operate using pull requests, the release notes automation should only list pull requests and not tickets. This way, we avoid duplication. We need to ensure that PRs are high quality (good description, labels, etc.)

**Comment by bric3** [comment] 2016-10-17 09:30
Probably, but people maybe interested in the ticket they filled. So PR are not enough. Maybe listing the related issue `#<number>` too might be better that ignoring them.

**Comment by szczepiq** [comment] 2016-10-17 12:58
The problem is that PRs are loosely linked to issues. E.g. there is no reliable way to identify what issue relates to given ticket.

**Comment by bric3** [comment] 2016-10-17 13:51
Indeed, maybe by _greping_ title and description ?

**Comment by szczepiq** [comment] 2016-10-17 13:56
Maybe. I'm looking for a simple solution. Perhaps we try with PRs only and see how it goes.

**Comment by TimvdLippe** [comment] 2017-11-04 15:46
The duplicate entries seem to be fixed now: https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md

**Closed by TimvdLippe** 2017-11-04 15:46 UTC
Labels: continuous integration
