### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by lwasyl** [mockito/mockito#2262] opened 2021-04-08 12:40 UTC
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.ReflectionMemberAccessor to constructor java.lang.Void()
WARNING: Please consider reporting this to the maintainers of org.mockito.internal.util.reflection.ReflectionMemberAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I don't know exactly what call causes it. This is with Mockito 3.8.0, Mockito-Kotlin 2.2.0, and
```
﻿openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

**Comment by TimvdLippe** [comment] 2021-04-08 12:45
Duplicate of #1325

**Closed by TimvdLippe** 2021-04-08 12:45 UTC
