### ISSUE TITLE
LICENSE URL in pom.xml is invalid

### ISSUE THREAD

**Issue by radistao** [mockito/mockito#1874] opened 2020-02-19 11:29 UTC
`mockito-core 3.2.4`

in the generated pom.xml published to Maven repository:
https://repo1.maven.org/maven2/org/mockito/mockito-core/3.2.4/mockito-core-3.2.4.pom

the URL to the license is invalid:
https://github.com/mockito/mockito/blob/master/LICENSE
referring to `master` branch, but presently this repo doesn't have master, but `release/3.x` default branch.

Should be easy to fix (however i get lost a bit in the gradle configurations, so can't make a quick PR)

**Comment by TimvdLippe** [comment] 2020-03-17 22:16
Duplicate of #1529

**Closed by TimvdLippe** 2020-03-17 22:16 UTC
