### ISSUE TITLE
mockito-android 2.26+ tries to use missing opentest4j exceptions

### ISSUE THREAD

**Issue by matejdro** [mockito/mockito#1716] opened 2019-05-24 08:44 UTC
It appears that Mockito `2.26+` on Android tries to use exceptions from OpenTest4j, even when OpenTest4j is not used, resulting in tests crashing due to exceptions classes not being found.

Steps to reproduce:

1. Open [MockitoAndroidDemo](https://github.com/mockito/mockito/files/3215946/MockitoAndroidDemo.zip) project in Android Studio
2. Run `ExampleInstrumentedTest.java` test on android device/emulator
3. Test will crash with `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/opentest4j/AssertionFailedError`

Lowering version to `2.25.0` fixes the issue

**Comment by TimvdLippe** [comment] 2019-05-24 11:20
@kriegfrj do you mind taking a look at this?

**Comment by kriegfrj** [comment] 2019-05-24 11:52
I can't promise to look at it swiftly. I've never run an Android emulator before, it'll take me a while to get set up.

In the meantime, @matejdro , if you could post the stack trace of the error that would help. I might be able to get a clue without seeing up the whole environment.

**Comment by matejdro** [comment] 2019-05-24 11:54
Here you go:

[stacktrace.txt](https://github.com/mockito/mockito/files/3216729/stacktrace.txt)

**Comment by kriegfrj** [comment] 2019-05-24 12:00
Thanks.

Looks like you've got some funky ClassLoader in there doing something odd. I'll try and look more closely later, possibly later in the weekend.

**Comment by kriegfrj** [comment] 2019-05-24 14:33
I've had a quick look and I haven't been able to get the emulator running easily to reproduce it myself. However, having had a closer look at the stack trace, I suspect that it is some kind of feature in the test harness (perhaps in AndroidJUnitRunner) that is supposed to detect and warn when your code tries to load classes that it can't find on its classpath. Attempting to load the OpenTest4J class is perfectly normal behaviour for this version of Mockito though, and the attempt is surrounded by a <tt>catch()</tt> which ordinarily would catch any error thrown.

As a workaround, you could try putting OpenTest4J on your classpath. You might lose the visual diff in case of failure though.

**Comment by matejdro** [comment] 2019-05-25 06:35
Here is my guess on what happens:

Exceptions catching for missing classes only [surrounds factory creation, not the actual exception creation](https://github.com/mockito/mockito/blob/28012a49cb1b1aab1b957ac5e7507dd8b807a47e/src/main/java/org/mockito/internal/junit/ExceptionFactory.java#L23). It is possible that Desktop JVM verifies all methods on class creation, but Android's runtime does not. And thus no exception is thrown there. Instead Android's runtime throws missing class exception when `create()` method is executed for the first time, which does not have`try/catch` around it.

**Comment by kriegfrj** [comment] 2019-05-25 14:12
I thought about your suggestion, but I don't think it fits with the stack trace that you provided. In the stack trace, there's no mentionit's clear that the line it's complaining about is line 24, in the static initializer for `ExceptionFactory`, when the factory implementation is actually created:

at org.mockito.internal.junit.ExceptionFactory.<clinit>(ExceptionFactory.java:24)

I expect a `ClassNotFoundError` to get thrown here when OpenTest4J is not on the class path. What is not expected is that this isn't caught by the surrounding `catch(Throwable)` statement. Which is why I think the android test framework is doing something funky.

If what you're suggesting were true, I'd expect line 27 to appear at the top of the stack trace, but it doesn't appear at all. According to the stack trace, it is failing before `create()` is even called, This scenario would also be contrary to the JVM spec (which, from memory, specifies that all the class's linkages should be resolved when the class is loaded, and not when a method is executed).

One way to test this would be to package up a JUnit test and deploy it as an APK into the emulator and run it directly, rather than as part of an instrumentation test. If you want to give that a try and let me know how you go we can analyse the result.

**Comment by kriegfrj** [comment] 2019-05-25 15:25
Ok @matejdro , I still haven't been able to get the Android Studio stuff working, but based on the above educated guess I've made a change that might do the trick. You can find this change under branch `1716-opentest4j-under-android` in my fork of Mockito (https://github.com/kriegfrj/mockito). If you could download, build and install this and give it a try and let me know if it fixes your problem, that would be much appreciated.

If it does fix your problem, I'll create a PR from this branch so that @TimvdLippe  or @mockitoguy can merge it. If not, I guess I'll go back to the drawing board...

**Comment by matejdro** [comment] 2019-06-05 06:02
Sorry for the delay. Any tips on how to build `mockito-android`? Running `gradlew build` only procudes `mockito-core` and I cannot find a way to switch it to android.

**Comment by matejdro** [comment] 2019-06-05 06:09
Never mind, figured it out (android project is in the `subprojects`) folder. 

It appears that using your branch fixes the issue. I no longer get the crash.

**Comment by kriegfrj** [comment] 2019-06-06 00:57
Thanks for verifying @matejdro. I have created a PR for this issue now (#1716).

Thank you so much for your help - I was dreading having to go through the process of getting the Android emulator working! I'm sure it would have been fun to try but (like most people) I'm a bit time poor...

**Comment by johnmahlon** [comment] 2019-07-18 20:09
I am also having this issue. I was running v3.0.0, but switching back to 2.25.0 fixed it.

**Comment by kriegfrj** [comment] 2019-07-19 00:08
> I am also having this issue. I was running v3.0.0, but switching back to 2.25.0 fixed it.

Sorry @johnmahlon, the fix for this was supposed to get merged into 3.0 but I dropped the ball. Hopefully it will get merged soon.

In the meantime, as a workaround, if you need Mockito >2.25.0 then you should be able to run it with any version of Mockito if you just put `org.opentest4j` on your runtime classpath.

**Comment by johnmahlon** [comment] 2019-07-19 00:21
@kriegfrj no problem. Our app isn’t production yet, so using 2.25 is definitely fine for now.

**Closed** 2019-07-19 10:25 UTC
