### ISSUE TITLE
Mocked annotated class extending Map returns null when accessed as Map

### ISSUE THREAD

**Issue by joevalerio** [mockito/mockito#1883] opened 2020-03-04 15:25 UTC
java-1.8.0_91
mockito-2.23.4
jackson-2.6.7

We have an extension of HashMap to allow jackson to serialize/deserialize.  I wrote some generic code to pull a dot path from nested maps, but ran into an issue where the mock object returns null if the mock is passed to a method as a sub-interface.  Here is a unit test that simplifies the issue.  The first two tests pass, but the third does not.

```
package test;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;
import java.util.HashMap;
import java.util.Map;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;

@RunWith(MockitoJUnitRunner.class)
public class TestMockito {

  @Mock
  JsonMap json;

  @Before
  public void setup() {
    when(json.get("test")).thenReturn("foobar");
  }

  @Test
  public void testJsonMap1() {
    assertEquals("foobar", json.get("test"));
  }

  @Test
  public void testJsonMap2() {
    assertEquals("foobar", getFromJsonMap(json, "test"));
  }

  @Test
  public void testJsonMap3() {
    assertEquals("foobar", getFromMap(json, "test"));
  }

  protected Object getFromJsonMap(JsonMap map, String key) {
    return map.get(key);
  }

  protected Object getFromMap(Map<String, Object> map, String key) {
    return map.get(key);
  }

  public static class JsonMap extends HashMap<String, Object> {

    private static final long serialVersionUID = 1L;

    @JsonAnyGetter
    public Object get(String key)
    {
        return super.get(key);
    }

    @JsonAnySetter
    public void set(String key, Object value)
    {
        super.put(key, value);
    }

  }

}
```

**Comment by joevalerio** [comment] 2020-03-04 15:27
I should have tried before submitting, but you can remove the Jackson Annotations and it still fails.

**Comment by SuricateMeli** [comment] 2020-03-15 13:27
Hello @joevalerio ,
The issue is resolved is you add this code in the setup method:
```java
Object obj = "test"; 
when(json.get(obj)).thenReturn("foobar");
````
Why ? Actually your method get into the JsonMap don't override the get method in the HashMap class because it not the same signature.
The get method in JsonMap class is set(String key) and in HashMap is get(Object key). Not the same method and as the only mehtod mocked is get(String key) you obtain null for get(Object key) called when you use parent class...

**Comment by TimvdLippe** [comment] 2020-04-13 13:21
Thank you @SuricateMeli for the great answer! Likely if you add `@Override` to your subclass implementation the compiler will explain what is going wrong. Closing per the above comment.

**Closed by TimvdLippe** 2020-04-13 13:21 UTC
