### ISSUE TITLE
With `mock-maker-inline`, `-parameters` are lost

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#695] opened 2016-10-16 12:40 UTC
I gave the new final class mocking feature a spin by configuring `mock-maker-inline` in the appropriate place, and by and large it does what it says on the tin: mocking of final classes does work indeed. Awesome!

But I found there's one unintended side-effect: constructor parameters as retained when compiling with Java 8's `-parameters` flag are lost. (We rely on this feature because we use [jackson-module-parameter-names](https://github.com/FasterXML/jackson-module-parameter-names).)

The following TestNG test illustrates the issue. Note that `test1`, `test2` and `test3` are executed sequentially, in that order. Note also that `test1` and `test3` are identical. When this class is compiled with  `-parameters` and when `mock-maker-inline` is enabled, then the first two tests pass (as they should), while the third fails.

```java
import static org.mockito.Mockito.mock;
import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public final class Test {
    static final class Dummy {
        public Dummy(final String dummyArg) {}
    }
    
    // Passes, because we compile with `-parameters`.
    @Test
    public void test1() throws NoSuchMethodException {
        final String param = Dummy.class.getConstructor(String.class).getParameters()[0].getName();
        assertEquals(param, "dummyArg");
    }

    // Passes, because we have configured `mock-maker-inline`.
    @Test(dependsOnMethods = "test1")
    public void test2() {
        @SuppressWarnings("unused")
        final Dummy d = mock(Dummy.class);
    }

    // Fails, because parameter names got lost.
    @Test(dependsOnMethods = "test2")
    public void test3() throws NoSuchMethodException {
        final String param = Dummy.class.getConstructor(String.class).getParameters()[0].getName();
        assertEquals(param, "dummyArg");
    }
}
```

**Comment by Stephan202** [comment] 2016-10-16 12:41
@raphw, I apologize if this bug should have been filed against Byte Buddy; I didn't dig that deep.

**Comment by Stephan202** [comment] 2016-10-16 12:45
Sorry, forgot to include the failure stacktrace:

```
java.lang.AssertionError: expected [dummyArg] but found [arg0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.example.Test.test3(Test.java:32)
	...
```

**Comment by szczepiq** [comment] 2016-10-16 14:36
Thanks a lot for trying out the incubating feature and reporting problems!!! This is really helpful for us in getting seamless support for "mocking unmockables".

**Comment by raphw** [comment] 2016-10-17 14:43
Byte Buddy is supposed to retain parameter names but it seems like I missed something. I will have a look and fix that as soon as I find the time.

**Comment by raphw** [comment] 2016-10-17 15:13
This is actually not a bug in either Byte Buddy or in Mockito but a bug in the JVM. When a class file transformer is activated, it supplies the class's byte code as a byte array. The parameter information is missing from this byte array; the VM does however not preserve the information when resolving the byte array for the class file transformer which is why the transformation goes missing.

This is however a problem for any Java agent on the VM and not Mockito specific. We can work around this by reading the original class file from the class loader, if available. However, this way we might undo other Java agents' transformations. Also, we cause a bunch of IO to read from the file system.

I do however think that this is the way to go. I will file a bug with the OpenJDK.

**Comment by bric3** [comment] 2016-10-17 15:20
Can't we embed this information using ASM (within Byte Buddy)?

**Comment by raphw** [comment] 2016-10-17 15:27
Byte Buddy does automatically preserve this information. The problem is that it is gone entirely from the class file. HotSpot needs to re-resolve the class file after it is read, I think the HotSpot team simply forgot to add the parameter context information when they added the feature in Java 7.

**Closed** 2016-10-17 15:30 UTC

**Comment by Stephan202** [comment] 2016-10-17 16:08
Thanks @raphw! Just built the artifact from source and all tests in our project now pass with `mock-maker-inline`. If/when you file a bug with OpenJDK , can you please also link it here? :)

**Comment by raphw** [comment] 2016-10-17 16:12
I reported it but those bugs are only filed when they pass QA. I will add the ticket once I receive a confirmation.

**Comment by raphw** [comment] 2016-10-17 16:13
PS: You can already use the new version: https://github.com/mockito/mockito

**Comment by szczepiq** [comment] 2016-10-18 03:47
@raphw, your support is fantastic, I'm so happy we're using ByteBuddy :)
