### ISSUE TITLE
Mockito-core test scope forces byte-buddy compile scope into module

### ISSUE THREAD

**Issue by Gerromie** [mockito/mockito#1662] opened 2019-03-13 18:00 UTC
Adding mockito-core to a maven module in test scope results in byte-buddy being brought in as a transient dependency in compile scope. This incorrectly changes any version of byte-buddy that might have been used by other modules (such as via swagger).

This appears on all versions of mockito-core tried from 2.18.3 up to 2.25.0.

It's expected that the test scope of mockito-core may use transient dependencies in the same scope but that the inclusion of the module would not override compile scope versions.

**Comment by TimvdLippe** [comment] 2019-03-19 20:40
What other scope would be more appropriate? We need `compile`, as we directly depend on ByteBuddy (just as we directly depended on CGLib)

**Comment by Gerromie** [comment] 2019-03-20 14:33
The primary concern is that I have a super pom that collects a few modules in a layout not unlike this:

- moduleA -- packaged as a jar that uses swagger as a compile time dependency (which uses byte-buddy of a specific version)
- moduleB -- packaged as a war that uses mockito for unit tests

When packaged, moduleB's WEB-INF/lib folder includes swagger and byte-buddy at the version that mockito-core requires (there's changed in byte-buddy that are breaking for mockito in current versions). I'd like to have the production war package include the version of byte-buddy that swagger needs, not mockito as mockito is only being used for test scope.

**Comment by mockitoguy** [comment] 2019-03-20 15:40
Hey @Gerromie,

According to you, what's the current and expected content of mockito-core pom.xml?

**Comment by Gerromie** [comment] 2019-03-20 16:13
I'd just like the mockito dependency to not override another dependency version so that I may ship my product with the version of byte-buddy that works with the version of swagger we're using. Does that answer the question @mockitoguy ?

To work around this issue, I had to downgrade the mockito version and add a dependencyManagement section to lock byte-buddy at the expected version. I have not found it necessary to manage any other dependencies in this way.

**Comment by mockitoguy** [comment] 2019-03-20 16:31
> Does that answer the question @mockitoguy ?

Not really, I still don't know what would you like to change in mockito-core's pom.xml.

**Comment by Gerromie** [comment] 2019-03-20 18:13
I'm not sure myself, which is why I mentioned the goal instead of a solution. The goal is to not have a test dependency change the version of a compile dependency included by another dependency.

**Comment by TimvdLippe** [comment] 2019-03-20 20:22
It feels like this is a duplicate of #1606 and I commented over there: https://github.com/mockito/mockito/issues/1606#issuecomment-473371126 TLDR: I am not sure what Mockito can do to work around this issue in Maven. It feels like we are the symptom, rather than the root cause of this issue. I am currently not aware of an alternative that prevents this solution, other than patching up the behavior of Maven.

**Comment by TimvdLippe** [comment] 2019-04-30 15:21
I am closing this issue, as there is currently nothing we can do to tell Maven to not force ByteBuddy in the compile scope. If at some point Maven updates their implementation to make this possible, we can patch our dependency specification.

**Closed by TimvdLippe** 2019-04-30 15:21 UTC

**Comment by benze** [comment] 2020-06-04 21:00
> What other scope would be more appropriate? We need `compile`, as we directly depend on ByteBuddy (just as we directly depended on CGLib)

Why wouldn't `test` scope suffice for that?  It would be then available during the test-compile phase.  With this current setup, my problem is that I now have `byte-buddy` packaged into my application during my WAR generation when it has no business being there.
