### ISSUE TITLE
thenThrow(Class) no longer creates new instances

### ISSUE THREAD

**Issue by brettkail-wk** [mockito/mockito#1875] opened 2020-02-19 15:59 UTC
As of #1162, `thenThrow(Class)` no longer creates new instances for each invocation.  We had tests that were reliant on that behavior; for example:
```
	@Test
	public void thenThrow() {
		Supplier<Object> r = mock(Supplier.class);
		when(r.get()).thenThrow(RuntimeException.class);
		RuntimeException first = null;
		for (int i = 0; i < 2; i++) {
			try {
				r.get();
			} catch (RuntimeException e) {
				if (first == null) {
					first = e;
				} else {
					first.addSuppressed(e);
				}
			}
		}
		if (first != null) {
			throw first;
		}
	}
```
These tests now fail:
```
java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.lang.Throwable.addSuppressed(Throwable.java:1043)
	at example.Test.thenThrow(Test.java:10)
```

**Comment by dean-burdaky** [comment] 2020-03-17 19:18
Hello, I've taken a look at the issue and it is still apparent in commit 560adf377677a4a2c658a0b24e2f9c2e0b373c20. It appears to be that `thenThrow(Class)` instantiates the Throwable when it is called rather than instantiating it upon mock interaction.

### Background
To why this leads to the behaviour described in the issue is that the Throwable is passed to `thenThrow(Throwable)` which instantiates a custom Answer with `new ThrowsException(throwable)` and passes into `thenAnswer(Answer)`. This Answer, of course, stores the Throwable and throws it with every repeat mock interaction.

Before the merge, `thenThrow(Class)` used to call `thenAnswer(Answer)` directly with its own custom Answer, ThrowsExceptionClass. This Answer instantiated the Exception with each mock interaction.

### Suggested Solution
My suggestion is to introduce an Answer similar to ThrowsExceptionClass described above (or a modified version of ThrowsException) and have `thenThrow(Class)` create that and call `thenAnswer(Answer)`.

I can think of two ways to implement the suggestion. Both ways involve storing the Class\<Throwable\> and using Objenesis to instantiate the Throwable in the new Answer class, however:

1. Create the new Answer class with similar code to ThrowsException but instead of throwing the stored Throwable it uses a new instance based of the stored Class\<Throwable\>.
2. Modify ThrowsException to use a protected getter method for the Throwable. Then extend ThrowsException with the new Answer for Class\<Throwable\> which overrides the getter method to instantiate a new Throwable.

Option 1 doesn't modify existing behaviour that works but has more duplicate code. Option 2 offers less duplicate code but modifies existing behaviour that works.

I prefer option 2.

**Comment by TimvdLippe** [comment] 2020-03-17 22:16
Happy to review a PR for this. We probably need to make a few iterations on the design, but agreed we can fix this issue.

However, if the necessary changes appear to be complicated, I am inclined to close this as working as intended.

**Closed** 2020-03-21 14:37 UTC
Labels: please contribute
