### ISSUE TITLE
Artifact ID changes

### ISSUE THREAD

**Issue by ming13** [mockito/mockito#1444] opened 2018-07-25 08:09 UTC
Since `2.20.0` Mockito Maven artifact IDs [have changed](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.mockito%22).

* `mockito-android` → `android`
* `mockito-inline` → `inline`
* `mockito-junit-jupiter` → `junit-jupiter`

Not sure if it is an intended change or not, so decided to clarify things a bit. So... Is it an intended change? It isn’t mentioned in the changelog.

**Comment by mockitoguy** [comment] 2018-07-25 17:45
It's a bug. Thank you for reporting!

**Comment by mockitoguy** [comment] 2018-07-25 17:50
@epeee, can you take a look at this?

**Comment by mockitoguy** [comment] 2018-07-26 03:37
Upstream bug in Shipkit: https://github.com/mockito/shipkit/issues/741

**Comment by epeee** [comment] 2018-07-26 04:12
@mockitoguy sorry, I was busy yesterday. 
I can have a look at the upstream bug in shipkit tomorrow.

**Comment by mockitoguy** [comment] 2018-07-26 16:33
There is some delay. Bintray log shows that the sync was successful. Let's wait until the end of the day.

Thanks for checking!

**Comment by mockitoguy** [comment] 2018-07-26 16:37
OSS repo has the right artifacts so I think it's just a delay before it's searchable in central. Proof - [pom.xml](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.mockito&a=mockito-inline&v=2.20.1&e=pom) in the Sonatype OSS 'release' repo.

Let's keep the ticket open until we add tests for the artifacts. @ming13, do you want to contribute a test that would verify artifact IDs? This should be a form of a Gradle task.

**Comment by mockitoguy** [comment] 2018-07-28 01:15
The issue is fixed in 2.20.1. I've added tests to prevent the issue in the future.

Thanks again for reporting!!!

**Closed by mockitoguy** 2018-07-28 01:15 UTC
