### ISSUE TITLE
Ambiguous method overloading - Spring RestTemplate

### ISSUE THREAD

**Issue by anumalasri** [mockito/mockito#1962] opened 2020-06-30 15:53 UTC
- [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

Hi,

Unable to mock method `exchange` defined in Spring `RestTemplate` using Mockito versions 3.3.3 and 3.3.12 and JDK v8

```
@Override
	public <T> ResponseEntity<T> exchange(String url, HttpMethod method,
			@Nullable HttpEntity<?> requestEntity, Class<T> responseType, Map<String, ?> uriVariables)
```

Tried to mock using below code snipect
``` 
method to from main code  
ResponseEntity responseEntity = restTemplate.exchange("endPoint", HttpMethod.GET, requestEntity, Map.class, [:])
------

mocking in test code 
doReturn(responseEntity).when(springRestTemplate).
		exchange( 
				Mockito.anyString(),
				Mockito.eq(HttpMethod.class),
				Mockito.any(HttpEntity.class),
				Mockito.eq(Map.class.class),
				Mockito.anyMap() )
```

We are getting below error and we tried different ways to mock 

```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.springframework.web.client.RestTemplate$MockitoMock$1786906310#exchange.
Cannot resolve which method to invoke for [class java.lang.String, null, null, null, class java.util.HashMap] due to overlapping prototypes between:
	[class java.lang.String, class org.springframework.http.HttpMethod, class org.springframework.http.HttpEntity, class java.lang.Class, interface java.util.Map]
	[class java.lang.String, class org.springframework.http.HttpMethod, class org.springframework.http.HttpEntity, class org.springframework.core.ParameterizedTypeReference, interface java.util.Map]
	org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
```

Not sure if its related to existing issues with Overloading ..  Suspicious on why its trying to identify some arguments as `null` and unable to resolve them with correct objects.

**Comment by TimvdLippe** [comment] 2020-09-13 22:57
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by TimvdLippe** [comment] 2020-12-02 19:19
Closing per the above comment.

**Closed by TimvdLippe** 2020-12-02 19:19 UTC
Labels: awaiting response

**Comment by tianjingle** [comment] 2022-08-12 04:41
maybe you could use `Mockitio.doAuswer`?

**Comment by ZqyDaoDao** [comment] 2024-04-01 06:15
mockito-core:4.11.0


 RestTemplate http = Mockito.mock(RestTemplate.class)
        Mockito.when(http.exchange(any(String.class), any(HttpMethod.class), any(HttpEntity.class), any(Class.class)))
                .thenReturn(mockResponseEntity);

出现了以下报错


Cannot resolve which method to invoke for [null, null, null, null] due to overlapping prototypes between:
	[class java.net.URI, class org.springframework.http.HttpMethod, class org.springframework.http.HttpEntity, class java.lang.Class]
	[class java.net.URI, class org.springframework.http.HttpMethod, class org.springframework.http.HttpEntity, class org.springframework.core.ParameterizedTypeReference]
