### ISSUE TITLE
Mocking JavaFX classes causes illegal reflective access warning

### ISSUE THREAD

**Issue by AstralStorm** [mockito/mockito#1933] opened 2020-05-14 08:41 UTC
I'm working on a project using OpenJFX 14, and tried to mock a controller class:
MyFxController mockController = Mockito.mock(MyFxController.class)

Class contains multiple JavaFX controls annotated with @FXML.

The mock results in the warning in the testcase:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.AccessibilityChanger (file:/C:/Users/r.szkodzinsk/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/3.3.10/7dbd244ef0c541d06ebd308a914bf2a0e10d123d/mockito-core-3.3.10.jar) to field javax.swing.JComponent.isAlignmentXSet

Tested with Mockito 3.3.3 and 3.3.10.

**Comment by TimvdLippe** [comment] 2020-08-12 20:56
Duplicate of #1325

**Closed by TimvdLippe** 2020-08-12 20:56 UTC
