### ISSUE TITLE
Mockito JUnit Jupiter extension does not correctly support parallel test execution

### ISSUE THREAD

**Issue by markusheiden** [mockito/mockito#1630] opened 2019-02-25 12:54 UTC
Sorry for not being able to provide the required information, but we just noticed that the MockitoExtension (mockito-junit-jupiter 2.24.5) leads to spurious test failures (e.g. due to calls to mocks not being recorded) when using "junit.jupiter.execution.parallel.enabled=true" with surefire. Prior we used our much simpler MockitoExtension which works fine in the same situation:

```java
public class MockitoExtension implements Extension, TestInstancePostProcessor, AfterEachCallback {
   @Override
   public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
      MockitoAnnotations.initMocks(testInstance);
   }

   @Override
   public void afterEach(ExtensionContext extensionContext) throws Exception {
      Mockito.validateMockitoUsage();
   }
}
```

**Comment by mockitoguy** [comment] 2019-03-04 15:06
Hey! Can you take a look at our FAQ wiki. We documented how Mockito supports parallel execution.

**Comment by markusheiden** [comment] 2019-03-04 21:12
I took a look at the wiki, but found just a very short section about parallel testing in the FAQ section. I issued the bug, because the parallel execution of whole test cases with JUnit 5 seams to be broken. I do not have any complex tests which use mocks in combination with multithreading.

Anyway this seams to be a problem of the MockitoExtension, not Mockito itself. Because with our simple JUnit 5 extension for Mockito, parallel testing with JUnit 5 works fine.

**Comment by SchulteMarkus** [comment] 2019-04-01 13:04
I got a similar issue. 
I have got a workaround, if only a few of your "Mockito"-test-classes in you testsuite are failing when running JUnit jupiter in parallel. You can execute those problematic tests using "SAME_THREAD" for avoiding Mockito concurrency issues.

```
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
@Execution(ExecutionMode.SAME_THREAD) # <--- Workaround
class SomeTest {
```

**Comment by markusheiden** [comment] 2019-04-05 22:10
To be a bit more specific, WantedButNotInvoked exceptions are thrown by verification calls failing, because of not recorded invocations: "Actually, there were zero interactions with this mock.".

**Comment by markusheiden** [comment] 2019-04-05 22:44
The main difference between the current and the simple implementation above is, that the simple one inits the mocks in postProcessTestInstance() whereas the current one inits them in beforeEach(). Any ideas why that might be a problem?

**Comment by mockitoguy** [comment] 2019-04-06 01:12
Hey guys, can you provide us a test that reproduces the problem? Thanks!

**Comment by SchulteMarkus** [comment] 2019-04-10 14:18
@mockitoguy Here you go: https://github.com/SchulteMarkus/mockito.bug1630

**Comment by mockitoguy** [comment] 2019-04-17 13:50
Thank you! The sample project looks great!

I looked at the code but I haven't had time to debug it. How does the JUnit5 parallel execution work? Are we sharing the test instance (and thus, sharing mocks, SUTs?).

**Comment by SchulteMarkus** [comment] 2019-04-18 08:19
You are welcome :-) 
I don't know details about JUnit's parallelization.

**Comment by ivocosta82** [comment] 2019-04-23 10:13
I'm having similar problems running my tests. the same_thread appears to fixed my tests. Symptoms include marking needed stubs as not needed and mocked classes being null in random test methods.

**Comment by dmitry-timofeev** [comment] 2019-06-12 15:21
> How does the JUnit5 parallel execution work? Are we sharing the test instance (and thus, sharing mocks, SUTs?).

By default not, and the user must be very explicit to enable sharing of the same test class instance with parallel execution enabled. I.e., even if parallel execution mode is enabled by default, and a test class is annotated with `Lifecycle.PER_CLASS`, its tests will still be executed sequentially _unless_ it is also annotated with `@Execution(CONCURRENT)`: https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution

I also bumped into this issue in our codebase, with some tests using `MockitoExtension` failing in parallel mode, and some working fine. Could not spot anything particularly special about the failing ones.

**Comment by liptga** [comment] 2019-09-25 15:07
I can confirm, that the problem exists. I also have tests using MockitoExtension and they fail in a non-deterministic way randomly only if Junit5 parralelization is used.

**Comment by liptga** [comment] 2019-09-25 16:21
Scenario:

1. JUnit 5 creates a single ClassExtensionContext for a multithreaded test, but each thread becomes an instance of the test class

If the MockitoExtension runs in multithreaded environment, then postProcessTestInstance will be called each time with the same ClassExtensionContext instance, but each time with a different testInstance.

**Comment by mockitoguy** [comment] 2019-09-27 07:58
This is really painful to debug but I'm making progress. What I found out is that "collectParentTestInstances()" is non-deterministic:

```
Thread[16] collectParentTestInstances() - returns: [org.mockito.AnotherTest@2bf588f6]
Thread[13] collectParentTestInstances() - returns: [org.mockito.AnotherTest@240da1f5, org.mockito.AnotherTest@6646267a]
Thread[17] collectParentTestInstances() - returns: [org.mockito.AnotherTest@6646267a]
Thread[14] collectParentTestInstances() - returns: [org.mockito.AnotherTest@f9b9d48]
```

Notice that AnotherTest@6646267a is processed twice. Effectively, initMocks() is called twice for that test instance, clearing up the invocations.

Do you have an idea how to fix collectParentTestInstances()?

**Comment by mockitoguy** [comment] 2019-09-27 08:18
Perhaps we drop the collectParentTestInstances() complexity and just keep the test instances in static ThreadLocal object in the extension. postProcessTestInstance() feeds the thread local state, beforeEach() consumes it. I don't know enough about the "context store" API, though.

**Comment by mockitoguy** [comment] 2019-09-28 02:51
I have a plan how to fix it. First, we need to upgrade junit-jupiter (#1788)

**Comment by liptga** [comment] 2019-09-28 20:21
@mockitoguy I am not sure why you have closed the issue. In the attached commit I cannot see the fix for the problem.

Context store API seems to be pretty simple to me, it is just a map in the context to store some information. The real question is what is this kind of context hierarchy used for in Junit 5 and how it behaves in case of nested tests or multithreaded tests, or even in multithreaded nested tests. I guess it could have some interesting beahaviour in case of parameterized (dynamic) tests. Probably it would be a good idea simply to ask the JUnit developers about this issue. Maybe they could provide some valuable feedback.

**Comment by mockitoguy** [comment] 2019-09-30 02:12
PR #1789 fixes the problem. This ticket got closed by accident. Thanks for looking into it!

**Closed** 2019-09-30 16:51 UTC
Labels: junit5

**Comment by liptga** [comment] 2019-10-01 08:34
Release is already published. See https://bintray.com/mockito/maven/mockito-development

**Comment by liptga** [comment] 2019-10-01 09:49
@mockitoguy when will this fix be released to maven central?

**Comment by TimvdLippe** [comment] 2019-10-01 10:33
I will publish a release today

**Comment by SchulteMarkus** [comment] 2019-10-01 11:52
I updated https://github.com/SchulteMarkus/mockito.bug1630 - seems to work without problems using Mockito v.3.1.0, thanks a lot!
I will delete https://github.com/SchulteMarkus/mockito.bug1630 within a few weeks.

**Comment by TimvdLippe** [comment] 2019-10-01 11:54
Publish to Maven Central failed yet again. I will need to contact sonatype again...

**Comment by TimvdLippe** [comment] 2019-10-01 11:56
(Although https://repo1.maven.org/maven2/org/mockito/mockito-core/3.1.0/ does exist, so it might just work)

**Comment by liptga** [comment] 2019-10-01 12:54
I can confirm, that the solution of 3.1.0 version works for all of the tests in my project. Still I don't understand how JUnit works, but it is fine now, since the tests work.

Thanks for your fast fix & release!
