### ISSUE TITLE
Different mocks are used for @Mock and @InjectMock in the same test class with JUnit 5 extension

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1346] opened 2018-03-25 12:31 UTC
I've been playing with the new JUnit 5 support in Mockito 2.17.0. I have found that with `@Mock` and `@InjectMocks` used in the same test class different mocks are injected. I would expect to have the same mock reused (as it works with JUnit 4 or manual `@Mock` initialization).

Sample code:
```
@ExtendWith(MockitoExtension.class)
public class SpaceShip5BugMiniTest {

    @InjectMocks
    private SpaceShip spaceShip;

    @Mock
    private TacticalStation tacticalStation;

    @Test
    public void shouldInjectMocks() {
        assertThat(tacticalStation).isNotNull();
        assertThat(spaceShip.getTacticalStation()).isEqualTo(tacticalStation);  
        //Bug ↑ - different mocks are use in @Mock and @InjectMock
    }
}
```

Error message:
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"tacticalStation (TacticalStation$MockitoMock$991606095@61d6015a)">
to be equal to:
 <"tacticalStation (TacticalStation$MockitoMock$991606095@b62d79)">
but was not.
Expected :tacticalStation
Actual   :tacticalStation
```

The minimal (non-)working example is available [here](https://github.com/szpak/code-examples-and-poc/tree/mockito2junit5-bug/mockito2-junit5).

@TimvdLippe Do you have an idea what could be wrong?

Mockito 2.17.0 (2.17.1 is not being released due to (https://github.com/mockito/shipkit/issues/679), junit-jupiter 5.1.0, OpenJDK 1.8.0_161, Linux.

### Checklist:
 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment] 2018-03-25 13:04
Hm that seems really weird. Could you please post the implementation of `TacticalStation` and `SpaceShip` (although I am assuming they are simple POJO's?)

**Comment by TimvdLippe** [comment] 2018-03-25 13:17
(Oh never mind, I missed the small link at the end of the example to https://github.com/szpak/code-examples-and-poc/tree/mockito2junit5-bug/mockito2-junit5/src/main/java/info/solidsoft/blog/mockito/junit5 )

**Comment by TimvdLippe** [comment] 2018-03-25 13:37
@szpak Please see https://github.com/mockito/mockito/blob/5e9a3c62fc1ca4cf12d5d19580613f418cebc895/subprojects/junit-jupiter/src/test/java/org/mockitousage/InjectMocksTest.java for a working test. I could make these tests fail with adding `final` to the field declaration, so that is what is going wrong. Removing `final` makes the tests pass.

What I do not understand is how this could work with JUnit 4, as we have not changed any of that code. We are completely reusing all of that logic.

**Comment by szpak** [comment] 2018-03-25 13:54
It also works with `final` if `MockitoAnnotations.initMocks(this);` is used. Therefore, I would suspect the way how it is triggered/executed in JUnit 5 extension.

**Comment by SeriyBg** [comment] 2018-03-26 08:55
@TimvdLippe @szpak I have debugged this issue a bit. Here is what I found: it does look like the problem is with triggering the same logic from `MockitoExtension.class`. 
The root cause of the problem is that `beforeEach` creates two `testInstances` of the same test class for each test. 
Looks like method `collectParentTestInstances` is adding the same testInstance to the list of test instances.
I can try to work on this issue if no one is assigned to is already.

**Comment by TimvdLippe** [comment] 2018-03-26 09:03
PRs appreciated!

**Comment by SeriyBg** [comment] 2018-03-26 09:45
Have added PR #1349 with the fix for the issue

**Closed** 2018-03-26 10:28 UTC
Labels: bug

**Comment by szpak** [comment] 2018-03-27 00:27
It works flawlessly. Thanks @SeriyBg!

@TimvdLippe As this bug can impact all those people prefering constructor injection, what do you thing about releasing the new minor version (e.g. after #1350 is hopefully merged :) ) to Maven Central?

**Comment by TimvdLippe** [comment] 2018-03-27 11:14
@szpak Yes after #1350 we will probably publish a new version. You can however already use the latest version from Bintray

**Comment by szpak** [comment] 2018-03-27 21:12
I know Tim that I can, but JUnit 5 support is a notable feature and having it working correctly in the latest non-development version (available in Maven Central) seems very sensible for me. Great, that we agree on releasing a new stable (but IHMO still 2.17.x) version soon.

**Comment by noel-yap** [comment] 2020-04-02 16:53
I'm seeing this same bug when using `SpringExtension.class` along with `MockitoExtension.class`:

```
@ExtendWith({MockitoExtension.class, SpringExtension.class})
public class InjectMocksTest {
  static class TacticalStation {}

  static class SpaceShip {
    private final TacticalStation tacticalStation;

    public SpaceShip(final TacticalStation tacticalStation) {
      this.tacticalStation = tacticalStation;
    }

    public TacticalStation getTacticalStation() {
      return tacticalStation;
    }
  }

  @InjectMocks
  private SpaceShip spaceShip;

  @Mock
  private TacticalStation tacticalStation;

  @Test
  public void shouldInjectMocks() {
    assertThat(tacticalStation).isNotNull();
    assertThat(spaceShip.getTacticalStation()).isEqualTo(tacticalStation);
    //Bug ↑ - different mocks are use in @Mock and @InjectMock
  }
}
```

This is using Mockito 3.1.0, JUnit 5.6.0, and Spring Boot 5.3.0.RELEASE.

**Comment by karthikaiselvan** [comment] 2020-04-18 14:23
> I'm seeing this same bug when using `SpringExtension.class` along with `MockitoExtension.class`:
> 
> ```
> @ExtendWith({MockitoExtension.class, SpringExtension.class})
> public class InjectMocksTest {
>   static class TacticalStation {}
> 
>   static class SpaceShip {
>     private final TacticalStation tacticalStation;
> 
>     public SpaceShip(final TacticalStation tacticalStation) {
>       this.tacticalStation = tacticalStation;
>     }
> 
>     public TacticalStation getTacticalStation() {
>       return tacticalStation;
>     }
>   }
> 
>   @InjectMocks
>   private SpaceShip spaceShip;
> 
>   @Mock
>   private TacticalStation tacticalStation;
> 
>   @Test
>   public void shouldInjectMocks() {
>     assertThat(tacticalStation).isNotNull();
>     assertThat(spaceShip.getTacticalStation()).isEqualTo(tacticalStation);
>     //Bug ↑ - different mocks are use in @Mock and @InjectMock
>   }
> }
> ```
> 
> This is using Mockito 3.1.0, JUnit 5.6.0, and Spring Boot 5.3.0.RELEASE.

Yes I am also facing this issue. Mine is also exactly the same scenario.
org.junit.jupiter:junit-jupiter-engine:5.6.0
org.springframework.boot:spring-boot-starter:2.2.6.RELEASE
org.springframework.boot:spring-boot-starter-test:2.2.6.RELEASE
org.mockito:mockito-junit-jupiter:3.1.0
