### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mangotang** [mockito/mockito#2371] opened 2021-07-30 17:09 UTC
> Hey,
>
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
>
> If this is about mockito usage, the better way is to reach out to
>
>  - stackoverflow : https://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

Mockito version: 1.10.19
Using this in the maven dependency:
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>

I am seeing this in my logs:
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/home/sbarkdull/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[ERROR] WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release

I can't tell if this is useful, please let me know if i can provide additional useful information. Love Mockito!

**Comment by TimvdLippe** [comment] 2021-07-30 17:18
Duplicate of #1325

**Closed by TimvdLippe** 2021-07-30 17:18 UTC
