### ISSUE TITLE
Mockito 3.0.1 and 3.0.2 are not available in maven central

### ISSUE THREAD

**Issue by iemejia** [mockito/mockito#1744] opened 2019-07-24 08:06 UTC
For ref.
https://search.maven.org/search?q=a:mockito-core
https://mvnrepository.com/artifact/org.mockito/mockito-core

**Comment by pzygielo** [comment] 2019-07-24 08:09
see #1738

**Comment by TimvdLippe** [comment] 2019-07-24 10:43
Closing as duplicate of #1738.

**Closed by TimvdLippe** 2019-07-24 10:43 UTC
