### ISSUE TITLE
MockHandlerImpl: Not thread safe reportOngoingStubbing

### ISSUE THREAD

**Issue by pumbabughunter** [mockito/mockito#1151] opened 2017-07-20 09:57 UTC
Mockito version="1.10.19"
However I've checked the sourses of 2.X and looks like  nothing has changed in MockHandlerImpl since that time.

**s2r**

I've written a test to reproduce the issue.
Since it's about a race condition to reproduce it u probably require to run the test several times in a row.
In Junit  (that I'm using) there are several ways how u can do it.

```
	@Test
	public void testDefaultResponse() throws Exception {
		String defaultAnswer = "DEFAULT ANSWER";
		Foo foo = Mockito.mock(Foo.class, (Answer<?>)invocation -> defaultAnswer);
		Thread checker = new Thread(
			() -> {
				while (true) {
					assertThat("DEFAULT ANSWER :",
						foo.bar("BUG"), Matchers.containsString(defaultAnswer));
				}
			});
		checker.start();

		Mockito.when(foo.bar(Mockito.argThat(Matchers.containsString("DOG"))))
			.thenReturn("PUG");
		assertThat("CUSTOM ANSWER :", foo.bar("DOG"), Matchers.containsString("PUG"));
	}

	public static class Foo {

		public String bar(String arg) {
			return "REAL METHOD";
		}
	}
```

**actual result**

```
Exception in thread "Thread-0" java.lang.AssertionError: DEFAULT ANSWER :
Expected: a string containing "DEFAULT ANSWER"
     but: was "PUG"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at com.devexperts.tos.test.tdaservice.ThreadSafetyTest.lambda$testDefaultResponse$1(ThreadSafetyTest.java:28)
	at java.lang.Thread.run(Thread.java:745)

java.lang.AssertionError: CUSTOM ANSWER :
Expected: a string containing "PUG"
     but: was "DEFAULT ANSWER"

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at com.devexperts.tos.test.tdaservice.ThreadSafetyTest.testDefaultResponse(ThreadSafetyTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

```

The thing is that while MockHandlerImpl handles new invocation.
In reports stub to the mocking process.

```
        OngoingStubbingImpl<T> ongoingStubbing = new OngoingStubbingImpl<T>(invocationContainerImpl);
        mockingProgress.reportOngoingStubbing(ongoingStubbing);

```

That in its turn we could get while defining an anwer for our own stub in org.mockito.Mockito#when
since is pulls from the same mocking process ongoing stub
(see  org.mockito.internal.MockitoCore#stub() )

```
    public IOngoingStubbing stub() {
        IOngoingStubbing stubbing = mockingProgress.pullOngoingStubbing();
        if (stubbing == null) {
            mockingProgress.reset();
            reporter.missingMethodInvocation();
        }
        return stubbing;
    }
```

So in my case here:

```
`
		Mockito.when(foo.bar(Mockito.argThat(Matchers.containsString("DOG"))))
			.thenReturn("PUG");

`
```
I can unexpectedly define an anwer for invocation that runs in my custom thread.

**Comment by szczepiq** [comment] 2017-07-21 07:14
Wow, thank you for identifying this corner case and supplying reproducible sample!

Let me try to explain the use case:

```Java
when(invocation).thenReturn(x)
```

1. "invocation" is triggered first because that's how java evaluates arguments. Mockito remembers this call in a thread local state as "last" invocation on any mock.
2. "when" method is invoked and Mockito removes last invocation from the thread local stack of all invocations on all mocks. This is the first moment when things can get interesting :) In your case, though, this is working ok because you are using a different thread, so thread local state deals with it.
3. After we pulled down the invocation from thread local state, Mockito knows the what is the mock object that we are trying to stub. I haven't dig that far in your sample test so I only have a theory what's happening next. I suspect that in Mockito we ignore the last invocation from thread local state and simply use the last method invoked on the stubbed mock as a base of stubbing. However, there is a thread that invokes methods on the mock in a loop, registering all those invocations. So, at the point of stubbing, Mockito stubs wrong method.

Given that my theory stands true, the problem could be fixable. I say "could" because we might be upsetting other use cases when fixing this one. Let's debug first and identify the root cause of the problem you reported. Can you help us doing it? Thanks again for reporting this!

**Comment by pumbabughunter** [comment] 2017-07-21 18:19
I feel like we are on the same wave. and looks like this is exactly what is happening.
I'll try to debug this to identify the cause..

**Comment by szczepiq** [comment] 2017-07-27 13:52
Great. Let me know if you need help!

**Comment by szczepiq** [comment] 2017-07-27 14:00
I pushed a test that demonstrates the problem (based on your great sample!) to branch "issue-1151". The test works in Mockito codebase (e.g. it does not use Java8). It might be helpful to debug with Mockito code. Commit in "issue-1151" branch: https://github.com/mockito/mockito/commit/2a846f323ff53ac2918608ca4d9bfa900ade9732

**Comment by techpavan** [comment] 2017-10-04 09:25
Hi @szczepiq , I have raised a PR https://github.com/mockito/mockito/pull/1193 which explains the issue further. Also went ahead to raise a PR https://github.com/mockito/mockito/pull/1194 which is supposed to give a fix for this issue. This fix is not really justified as I believe some synchronized access control is necessary, but not exactly sure on where and how to provide that. If you can guide me, I can incorporate changes and update the PR.

**Comment by mockitoguy** [comment] 2017-10-15 15:19
Let's avoid working on this enhancement. See my comment: https://github.com/mockito/mockito/pull/1200#issuecomment-336717814

Thank you for the time reporting and putting together the PR!!!

**Closed by mockitoguy** 2017-10-15 15:19 UTC
Labels: please contribute

**Comment by eyalroth** [comment] 2018-05-17 23:12
Kind'a late into the party, but I just encountered this behavior myself. I'm using Mockito to test akka actors (in Scala), which are inherently asynchronous, and I'm trying to avoid akka's testing framework since I believe it just alienates the actors even further away from "regular" code. 

Anyhow, this might not be the most common use-case, but I did stumble upon it just now. I've also been doing a lot of work with Mockito lately--extending it for my own use (no fork, just added code to my project)--and I was wondering if there could be a much easier way accessing the real invocations / stubbings / verifications.

Instead of wrapping a mock with one non-thread-safe proxy handler, why not wrap it with a proxy per use-case? One for real invocations, one for stubbing and one for verifications.

I would've loved doing something like this:
```
when(myMock).doSomething(matcher()).thenReturn(value)
```
This way, `when` would actually return a totally different handler than the one for the real invocations, and it could record stubbing without any interruptions from neither real invocations nor verifications. Same goes for the other use-cases.

Obviously it is still the responsibility of the users to make sure to synchronize between their stubbing and actual invocations (if they invoke the real mock before stubbing it then there's nothing Mockito can really do about it).

I understand though that  this is not exactly possible with Java (although I believe it would be possible with Scala's macros), but it could be possible with the following syntax:
```
return(value).when(myMock).doSomething(matcher()) // doSomething can just return null
```
The latter syntax is also more safe in terms of stubbing `void` methods with answers if I'm not mistaken.

@mockitoguy Any thoughts on the subject?

**Comment by mockitoguy** [comment] 2018-05-23 02:53
Hey @eyalroth! Thank you for your feedback. I checked what I wrote before and my preference has not changed. I'm not sure what is your suggestion/recommendation. We already have doReturn() syntax in our public API.

**Comment by eyalroth** [comment] 2018-05-23 11:34
@mockitoguy My suggestion is quite a re-factor to underlying mechanism; that is, to break the mock-handler into 3 separate handler (per mock), which will be able to "communicate" with each via synchronized methods. This way each handler could handle invocations on its own separate from the other handler, thus making each of the use-cases (real, stub, verify) much more independent.

In order to achieve this though, both `when` and `verify` methods (or any other "entry points" to these modes) would have to return a different instance of the object. For instance, invoking `verify(mock)` would not return the mock itself like it does today (`verify(mock) != mock`). 

This is not possible with `when`. Well, it is possible to make this syntax work - `when(mock).doSomething(matcher())` - but then `doSomething` cannot return an `OngoingStubbing` like `when` does today; therefore, only a `do->when->method` approach can work here.
