### ISSUE TITLE
mockito 1.9.5 or 1.10.17  can not passed junit test when use generic class

### ISSUE THREAD

**Issue by cloudtrends** [mockito/mockito#150] opened 2014-12-30 07:08 UTC
let's has below assumpution test environments :

your can get demo project at:
https://github.com/cloudtrends/jstudy

https://github.com/cloudtrends/jstudy/tree/master/src/com/test

1.  public abstract class ParentClz<T extends ParentClz<T,U>, U> 
2.  public class Child extends ParentClz<Child,String>

3. public class ChildApi 
     just include one method:
     
	public Child addChild(){
		return new Child();
	}

4. test code can not passed:
   ChildApi api = mock(ChildApi.class, RETURNS_DEEP_STUBS );
   Child c = mock(Child.class, withSettings().verboseLogging());

   Child cDirect = api.addChild();
Child cu = cDirect.create();
 when( cu  ).thenReturn(c);

5. errors as :
java.lang.StackOverflowError
	at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.hashCode(Unknown Source)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.getEntry(Unknown Source)
	at java.util.HashMap.get(Unknown Source)
	at org.mockito.internal.util.reflection.GenericMetadataSupport.getActualTypeArgumentFor(GenericMetadataSupport.java:182)
	

or errors in 1.9.5

java.lang.ClassCastException: com.test.ParentClz$$EnhancerByMockitoWithCGLIB$$c2a01047 cannot be cast to com.test.Child
	at com.test.ChildTest.testCreate(ChildTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by bric3** [comment] 2015-01-05 15:53
Hi @cloudtrends,

I'm not how to reproduce your problem from the code snippet (even in the sample project).
Have you tried Mockito 1.10.19, there have been fixes regarding the `StackOverflowError`.

The ClassCastException in 1.9.5 is probably because this version is much less aware of generics, even with deep stubs you need to stub each call returning a parameterized type. Remember that at this time of writing Java has type erasure which means in many cases types are not available at runtime.

**Comment by cloudtrends** [comment] 2015-01-18 02:10
Hi @bric3 

I had switch mockito version from : 1.10.17 to 1.10.19 , the JUnit test result as below:


1. StackOverflowError  is gone 
2. But , ClassCastException still occurred again :

    the Child instance call  method  in  ParentClz , in which method return a new instance of child .



 java.lang.ClassCastException: com.test.ParentClz$$EnhancerByMockitoWithCGLIB$$eee34e0a cannot be cast to com.test.Child
	at com.test.ChildTest.testCreate(ChildTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by bric3** [comment] 2015-01-18 09:21
Hi,
I don't know exactly your code, the sample project don't don't really show precisely the problem, as you know in Java generics works with erasure, that means they are only known at runtime. If the type is not present in some some way, mockito cannot find the right type. That means that you may have to stub manually this call.

**Comment by bric3** [comment] 2015-02-21 13:37
Closing as no feedback from reporter

**Closed by bric3** 2015-02-21 13:37 UTC
