### ISSUE TITLE
JVM Crash with newest mockito version

### ISSUE THREAD

**Issue by eheimbuch** [mockito/mockito#2043] opened 2020-09-15 07:20 UTC
Hello guys,

recently we updated our mockito version to the newest (from 2.28.2 to 3.5.10) and now we get JVM crashes when running all unit tests. Running only a couple of tests is fine. This error occurs with java 11 but not with java 8. We have tried different jdks like adoptopenjdk, zulu and openjdk with java 11 but it still crashes. We also tried to update the maven-surefire-plugin and junit to the newest versions but it also had no effect. Interestingly it crashes each time on the same unit test, but it is a different test on each dev machine. We suspect there might be a bug in bytebuddy. See the attachments for further information.

Thanks in advance.

Our setup is:
Ubuntu 20.04
Java 11
[Failing Tests](https://github.com/scm-manager/scm-manager/tree/develop/scm-webapp) with `mvn clean test`
![Stacktrace](https://user-images.githubusercontent.com/50202942/93176514-a90ed080-f731-11ea-8a6d-a1cc5f8e9aba.png)
[hs_err.log](https://github.com/mockito/mockito/files/5222998/hs_err_pid37244.log)

**Comment by raphw** [comment] 2020-09-15 09:02
Could you try a reproduction? Looks like a JVM bug to me. Does it occur with Java 14?

**Comment by sdorra** [comment] 2020-09-15 09:05
@raphw I can reproduce the bug on osx with java 14.

**Comment by raphw** [comment] 2020-09-15 09:12
Can you share the reproduction? There's one verification error fix in the piprleline already.

**Comment by sdorra** [comment] 2020-09-15 09:53
[hs_err_pid47695.log](https://github.com/mockito/mockito/files/5224048/hs_err_pid47695.log)

**Comment by eheimbuch** [comment] 2020-10-05 07:18
Hey @raphw, 
did you find out anything yet? Can we help you in any way to find the error?

**Comment by raphw** [comment] 2020-10-10 21:31
Sorry for not getting back earlier. The error seems to point out an error around an internal assumption. Do you have a reproduction that I can run to get the same error with executing code? This would allow filing a bug report.

Does the same error occur when using Java 15?

**Comment by pfeuffer** [comment] 2020-10-12 07:00
Hi @raphw , thanks for your answer!

If it is okay for you, you could clone SCM-Manager from GitHub (https://github.com/scm-manager/scm-manager.git). To reproduce the error, you just have to build the module "scm-webapp" and run its tests, all dependencies will be fetched from the internet:

```
./mvnw clean install -pl :scm-webapp
```

This can be reproduced in a Docker container, too, just with this simple `Dockerfile`:

```
FROM ubuntu:18.04

RUN apt update \
    && apt install -y git wget \
    && git clone https://github.com/scm-manager/scm-manager.git \
    && wget -qO- https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz \
       | tar xvzf -
RUN cd scm-manager && git checkout 4f8ff46

ENV JAVA_HOME=/jdk-15

RUN cd scm-manager && ./mvnw clean install -pl :scm-webapp
```

As you can see, the error is reproducable with OpenJDK 15, too.

The concrete test case varies between our machines.

Thanks again for your help!

**Comment by raphw** [comment] 2020-10-13 06:55
I followed the steps and got to the point of:

    08:54:15.382 [main] ERROR sonia.scm.web.i18n.I18nServlet - Error on getting the translation of the plugins
      java.io.IOException: failed

**Comment by pfeuffer** [comment] 2020-10-13 08:09
You are right, I get the same error in the log. This results from one of the unit tests, but is of no relevance.

On my machine the relevant part with the build failure follows after these lines and look like the following:

```
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 642, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.381 s
[INFO] Finished at: 2020-10-13T09:51:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project scm-webapp: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/rene/development/cloudogu/scm-manager/scm-webapp/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/rene/development/cloudogu/scm-manager/scm-webapp && /usr/lib/jvm/openjdk-15/bin/java -jar /home/rene/development/cloudogu/scm-manager/scm-webapp/target/surefire/surefirebooter3437009735565373283.jar /home/rene/development/cloudogu/scm-manager/scm-webapp/target/surefire 2020-10-13T09-50-42_185-jvmRun1 surefire4434703208957766094tmp surefire_02875872410000133872tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] sonia.scm.api.v2.resources.GroupRootResourceTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/rene/development/cloudogu/scm-manager/scm-webapp && /usr/lib/jvm/openjdk-15/bin/java -jar /home/rene/development/cloudogu/scm-manager/scm-webapp/target/surefire/surefirebooter3437009735565373283.jar /home/rene/development/cloudogu/scm-manager/scm-webapp/target/surefire 2020-10-13T09-50-42_185-jvmRun1 surefire4434703208957766094tmp surefire_02875872410000133872tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] sonia.scm.api.v2.resources.GroupRootResourceTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
```

Do you get a successful build in the end?

**Comment by raphw** [comment] 2020-10-18 21:52
Bug in HotSpot: https://bugs.openjdk.java.net/browse/JDK-8254969

**Comment by TimvdLippe** [comment] 2020-12-01 18:42
Closing per the above comment.

**Closed by TimvdLippe** 2020-12-01 18:42 UTC
