### ISSUE TITLE
Release cycles?

### ISSUE THREAD

**Issue by StefanOltmann** [mockito/mockito#2177] opened 2021-01-15 11:27 UTC
Hi,

I'm watching releases of this project as I use it for my unit test mocking and always want to stay on the latest version.

I noticed that there are a lot of releases triggered automaticly by github-actions.

So some releases like the recent one from v3.7.4 to v3.7.5 only contain typos in JavaDoc.

Is this really worth a new release?

Please consider to release less often to reduce watch notification spam.

Kind regards,

Stefan

**Comment by TimvdLippe** [comment] 2021-01-15 11:59
I think this is a duplicate of #595 and is documented at https://github.com/mockito/mockito/wiki/Continuous-Delivery-Details#betas We recommend watching for Maven Central releases, which we publish roughly every month. @mockitoguy any more thoughts on this?

**Comment by StefanOltmann** [comment] 2021-01-15 12:06
> We recommend watching for Maven Central releases, which we publish roughly every month.

Okay, thank you!

I will follow this advice.

**Closed** 2021-01-15 22:55 UTC
