### ISSUE TITLE
Java 9 compatibility 

### ISSUE THREAD

**Issue by rarathore** [mockito/mockito#1116] opened 2017-06-08 11:47 UTC
Hi Team
	As you know Java9 release date is coming near (End of July 2017), So Please let me know whether you have any plan to incorporate Java 9 related changes in your libs,
Thanks a lot
Rajendra Rathore

**Comment by TimvdLippe** [comment] 2017-06-08 11:49
Closing as duplicate of #520

**Closed by TimvdLippe** 2017-06-08 11:49 UTC

**Comment by bric3** [comment] 2017-06-08 13:39
So the answer is yes. Also note that Java 9 release has been postponed to septembre in order to fix remaining module system issues. The news came yesterday.
