### ISSUE TITLE
`LenientCopyTool` silently fails to copy fields

### ISSUE THREAD

**Issue by hisener** [mockito/mockito#2698] opened 2022-07-01 10:48 UTC
👋 Not a Mockito bug per se, but a tiny debug logging suggestion.

Consider the following code:

##### MockitoSpyCompletableFuture.java
```java
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.mockito.Mockito;

final class MockitoSpyCompletableFuture {
  @Test
  @Timeout(3)
  void spyCompletableFuture() throws InterruptedException {
    CountDownLatch latch = new CountDownLatch(1);
    CompletableFuture<Void> future = Mockito.spy(CompletableFuture.completedFuture(null));

    future.thenAccept(unused -> latch.countDown());
    latch.await();
  }
}
```

This code works perfectly fine until JDK 17.

```
curl -LO https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
curl -LO https://repo1.maven.org/maven2/org/mockito/mockito-core/4.6.1/mockito-core-4.6.1.jar
curl -LO https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.10/byte-buddy-1.12.10.jar
curl -LO https://repo1.maven.org/maven2/org/objenesis/objenesis/3.2/objenesis-3.2.jar

java -version
javac \
  -classpath junit-platform-console-standalone-1.8.2.jar:mockito-core-4.6.1.jar \
  MockitoSpyCompletableFuture.java
java \
  -jar junit-platform-console-standalone-1.8.2.jar \
  -classpath mockito-core-4.6.1.jar:byte-buddy-1.12.10.jar:objenesis-3.2.jar:. \
  -c MockitoSpyCompletableFuture
```

```
openjdk version "15.0.7" 2022-04-19
OpenJDK Runtime Environment Zulu15.40+19-CA (build 15.0.7+4-MTS)
OpenJDK 64-Bit Server VM Zulu15.40+19-CA (build 15.0.7+4-MTS, mixed mode)

[         1 tests successful      ]
[         0 tests failed          ]
```

However, in JDK 17, it times out after 3 seconds.

```
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)

Failures (1):
  JUnit Jupiter:MockitoSpyCompletableFuture:spyCompletableFuture()
    MethodSource [className = 'MockitoSpyCompletableFuture', methodName = 'spyCompletableFuture', methodParameterTypes = '']
    => java.util.concurrent.TimeoutException: spyCompletableFuture() timed out after 3 seconds
       org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)

[         0 tests successful      ]
[         1 tests failed          ]
```

It fails because JDK 17 encapsulates the internals of the JDK. See also [JEP 403](https://openjdk.org/jeps/403). We need to add `--add-opens java.base/java.util.concurrent=ALL-UNNAMED` to work around.

```
java \
  --add-opens java.base/java.util.concurrent=ALL-UNNAMED \
  -jar junit-platform-console-standalone-1.8.2.jar \
  -classpath mockito-core-4.6.1.jar:byte-buddy-1.12.10.jar:objenesis-3.2.jar:. \
  -c MockitoSpyCompletableFuture

[         1 tests successful      ]
[         0 tests failed          ]
```

However, it's not clear to see why the test failed in JDK 17 since the `IllegalAccessException` was swallowed and there is no relevant log. So, I think adding log in the catch block below would help understanding the test failure.

https://github.com/mockito/mockito/blob/2a66c6366a515273bbb25fb36b5915f1925833a0/src/main/java/org/mockito/internal/util/reflection/LenientCopyTool.java#L40-L45

It's worth mentioning that JDK 15 gives a warning about illegal reflective access, but it wasn't the first thing I checked. 😅 A log statement like the following would have saved me an hour:

```java
LOG.debug("Failed to copy field '{}'", field, t);
```

**Comment by TimvdLippe** [comment] 2022-07-01 19:18
For JDK 17+, we are planning to switch to `mockito-inline` as the default mockmaker (#2589) as the subclass mockmaker indeed is not sufficient for these versions. Therefore, I think we can close this as duplicate of #2589, WDYT?

**Comment by hisener** [comment] 2022-07-04 09:13
Sounds good to me. However, if we are going to keep this code, I'd say having a log statement is still worth it. It's a one-line fix anyway. 🙂

**Comment by TimvdLippe** [comment] 2022-10-22 12:04
Mockito typically doesn't log, but explicitly fails in the case of incorrect behavior. In this case, while it is working as expected, switching to `mockito-inline` will be the best longterm fix.

**Closed by TimvdLippe** 2022-10-22 12:04 UTC
