### ISSUE TITLE
Race Condition when Stubbing

### ISSUE THREAD

**Issue by keeyzar** [mockito/mockito#1538] opened 2018-11-21 18:40 UTC
Hello together,

I've encountered an annoyance with Mockito and I'm thinking it's a race condition..
Whats happening?
A stub is returning either null or the object provided in the stub. Code is not changed between test runs.

I've encountered the bug in my own source code and tried to reproduce, the provided test
will either run green (correct stubbing behaviour), WHEN RUN IN DEBUG
or run red, (return null, not returning the configured stubb), WHEN RUN IN NORMAL

-- why do I suspect that's a race condition?
I've got a nearly identical code in my real codebase, and there the test will either fail or go green without debug mode.
But please, see for yourself - the zip contains necessary project setups.

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

Env:
OS: Linux 4.9.0-8-amd64
Java: 
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
IDE:
IntelliJ
Mockito:
mockito 4.10.19
JUnit:
JUnit 4.12

Stacktrace Mockito:
`java.lang.NullPointerException
	at ClassUnderTest.doStuf(ClassUnderTest.java:10)
	at ClassUnderTestTest.doTest(ClassUnderTestTest.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

[reproducer.zip](https://github.com/mockito/mockito/files/2605368/reproducer.zip)

**Comment by bric3** [comment] 2018-11-21 21:53
Hi

Thanks for reaching us. The attached codebase uses mockito 1.10.19, Mockito is now at version 2.23.4, and the JDK is version 11, mockito fully supports JDK 11 from version 2.23 at the very least (thanks to byte-buddy).

**Comment by keeyzar** [comment] 2018-11-22 02:55
wow. I thoroughly failed attaching the codebase. Sorry for that inconvenience
I added 2.23.24 of mockito to the dependency.
Still the exact same behavior. This time I could reproduce this behavior on another PC, but same specs, tho. (debian, jdk11)
[reproducer.zip](https://github.com/mockito/mockito/files/2606436/reproducer.zip)

**Comment by bric3** [comment] 2018-11-23 17:32
OK got it, it's because `ClassA` implements `InterfaceB` and the test declares 2 mocks `ClassA` and `InterfaceB`, this confuses the simple injection mechanism which doesn't know which mock to inject in `ClassUnderTest`. And since reflection doesn't guarantee the order of fields, you may see the test failing one time and succeeding the other.

This has nothing to do with race conditions.

There's no way to really fix that with an automatic mock dependency injection, it could probalby even confuses other DI libs like Spring. Your only options are
* either make `ClassA` to not implement `InterfaceB`
* or perform the wiring manually since this is a bit not usual setup

Closing this ticket as this is not a bug really.

**Closed by bric3** 2018-11-23 17:32 UTC
Labels: question
