### ISSUE TITLE
Why the mockito is not compatible with jacoco?

### ISSUE THREAD

**Issue by Nymph-fan** [mockito/mockito#969] opened 2017-02-27 08:49 UTC
Hello:
      I'm glad to use mockito ,but when I use  jacoco to count the coverage of unit test. The coverage always be 0.Is there any way to solve it?

**Comment by TimvdLippe** [comment] 2017-02-27 08:58
Mockito should be compatible with jacoco. What is the version you are loading and could you create a minimal reproducible gist?

**Comment by Nymph-fan** [comment] 2017-02-27 09:36
Thanks for reply. In maven configuration I use ` <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.9.0</version>
            <scope>test</scope>
        </dependency>`

the  source code is
`
public HelloWorld() {
    }
    public String testMethod1() {
        return "Hello World";
    }
    public int addMethod(int a, int b) {
        return a + b;
    }
`

the test code is 
`  @Test
    public void testMethod1(){
        HelloWorld mock=mock(HelloWorld.class);
        when(mock.testMethod1()).thenReturn("Hello World");
        String resutlt=mock.testMethod1();
        Assert.assertEquals(resutlt,"Hello World");
    }`

the I use jacoco-maven-plugin to Statistical coverage，but the result of coverage  is zero

**Comment by TimvdLippe** [comment] 2017-02-27 09:41
Version 1.9.0 is quite old. Could you upgrade to a more recent version, preferably [2.7.12](http://search.maven.org/#artifactdetails%7Corg.mockito%7Cmockito-core%7C2.7.12%7Cjar) or if you can not, [1.10.19](http://search.maven.org/#artifactdetails%7Corg.mockito%7Cmockito-core%7C1.10.19%7Cjar). Also you are using `mockito-all` which is deprecated. Please use `mockito-core` instead.

**Comment by bric3** [comment] 2017-02-27 10:18
@Nymph-fan Note this may depend on the jacoco version as well.

**Comment by Nymph-fan** [comment] 2017-02-27 12:05
@bric3 @TimvdLippe  I update `mockito-core`  version to 1.10.19, `jacoco-maven-plugin` to 0.7.7。But the coverage is still 0. So I think  jacoco can't count the coverage of unit test through `mock`  frame or method

**Comment by bric3** [comment] 2017-03-01 10:42
@Nymph-fan I cannot say what's wrong, however we don't support mockito 1.x anymore, the mock generation engine was CGLIB and may have issues regarding coverage. Mockito 2.x now uses ByteBuddy instead.

**Comment by TimvdLippe** [comment] 2017-03-10 20:18
Since 1.x is not supported anymore and we have not received any issues with Mockito 2.x + Jacoco, I am going to close this issue. If you do encounter any issues with 2.x, please reopen. Thank you for your time!

**Closed by TimvdLippe** 2017-03-10 20:18 UTC
Labels: question

**Comment by HanumanGokavarapu** [comment] 2017-07-12 17:25
Even with  mockito2.x+jacoco we are not getting coverage ,Coudl you please provide sample projecst

**Comment by Helias-Criouet** [comment] 2018-02-02 17:16
For me the issue was in the Jacoco gradle task. The `classDirectories` needed to point to the `${buildDir}/intermediates/classes` folder.

**Comment by Fernal73** [comment] 2020-06-22 11:38
I'm using Mockito 2.0.2-beta and no jacoco coverage is counted via the Maven Surefire plugin.
